/* Public playtest developer controls. Not authentication and not a player progression system. */
(function(g){'use strict';const A=g.GuildAdminTools,R=g.GuildRules,P=g.GuildProgression,D=g.GuildDungeon,F=g.GuildAdventureFlow,V=g.GuildCharacterPresentation;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tabs=[['resources','Ressourcen'],['members','Mitglieder'],['recruit','Recruitment'],['items','Items'],['quests','Quests'],['dungeon','Dungeon'],['combat','Combat / Animation'],['save','Save'],['debug','Debug Info']];
// Ordinary Combat ticks must not invalidate a human confirmation every 250 ms.
// Membership, gear, rewards, status transitions and all non-transient fields remain guarded.
function confirmationKey(state){const s=R.clone(state);for(const d of D?.runs(s)||[])if(d.status==='Combat'&&d.current){d.lastTime=0;d.current.pending=0;d.current.state=null;}return JSON.stringify(s);}
const reasons={
 'storage-clear':'Alle freien Items und unzugewiesenen Heiltränke löschen? Getragene Ausrüstung und zugeteilte Tränke bleiben erhalten.',
 'starter-reset':'Die unveränderte Save-Struktur erlaubt eine offene Starterrunde nur in einer leeren Gilde. Diese Aktion startet deshalb eine NEUE GILDE: Mitglieder, Gruppen, Quests, Dungeonhistorie, Gold, XP, Items sowie Primary und Backup werden zurückgesetzt.',
 'new-guild':'Die gesamte Gilde sowie Primary und Backup zurücksetzen? Mitglieder, Gruppen, Quests, Gold, XP, Items und Dungeonhistorie gehen verloren.',
 'member-restore':'DEV-ONLY: Dieses verstorbene Mitglied wieder einsatzfähig machen? Historische Ergebnisse bleiben erhalten, frühere Items werden nicht dupliziert. Keine reguläre Wiederbelebungsmechanik.',
 'dungeon-clear':'Alle Dungeonläufe, ihre Historie und offenen Dungeonbelohnungen löschen? Gebuchte Ressourcen und bisherige Lebensfolgen bleiben erhalten. Aktive Gruppen werden frei. Dungeon-Test-IDs beginnen danach neu.',
 'save-primary-delete':'Primary Save löschen? Der laufende Speicherzustand und ein vorhandenes Backup bleiben erhalten. Autosave wird bis zum ausdrücklichen Fortsetzen oder Reload pausiert.',
 'save-backup-delete':'Backup Save löschen? Primary und laufender Zustand bleiben erhalten. Autosave wird bis zum ausdrücklichen Fortsetzen oder Reload pausiert.',
 'save-corrupt':'TEST-ONLY: Aktuellen gültigen Stand als Backup sichern und den Primary absichtlich beschädigen? Autosave pausiert. Beim Reload kann der bestehende Backup-Fallback geprüft werden.'
};
function create(host){
 const $=s=>document.querySelector(s),dialog=$('#admin-dialog');let tab='resources',feedback='',error=false,pending=null,serial=0,probe=null,scene=null,probeTime=0;
 const selected={member:'',party:'',quest:'',run:'',actor:'',pose:'Idle'};
 const button=(label,op,args={},disabled=false,danger=false)=>`<button type="button" data-action="admin-run" data-op="${op}" ${Object.entries(args).map(([k,v])=>`data-${k}="${esc(v)}"`).join(' ')} ${disabled?'disabled':''} class="${danger?'danger':'quiet'}">${label}</button>`;
 const note=s=>`<p class="admin-note">${s}</p>`,grid=s=>`<div class="admin-buttons">${s}</div>`;
 function select(key,label,rows){if(!rows.some(r=>r.id===selected[key]))selected[key]=rows[0]?.id||'';return `<label class="admin-select">${label}<select id="admin-${key}" aria-label="${label}">${rows.length?rows.map(r=>`<option value="${esc(r.id)}" ${r.id===selected[key]?'selected':''}>${esc(r.label)}</option>`).join(''):'<option value="">Keine Auswahl verfügbar</option>'}</select></label>`;}
 const ms=s=>s.members.map(a=>({id:a.id,label:a.name+' · '+R.classes[a.cls].name+' · F'+a.level+(a.dead?' · TOT':a.recovery>host.get().clock?' · verletzt':'')+(R.locked(s,a.id)?' · im Einsatz':'')}));
 const ps=s=>s.parties.map(p=>({id:p.id,label:p.name+' · '+p.members.length+' Mitglieder'+(R.partyLocked(s,p.id)?' · gebunden':'')}));
 function panel(){const {state:s,clock,saveMessage,storage}=host.get(),memberSelect=()=>select('member','Mitglied',ms(s)),partySelect=()=>select('party','Gruppe',ps(s));
  if(tab==='resources')return `<h3>Ressourcen für den Teststand</h3>`+grid([100,500,1000].map(amount=>button('+'+amount+' Gold','gold-add',{amount})).join('')+button('Gold auf 0 setzen','gold-zero')+[50,250].map(amount=>button('+'+amount+' Gilden-XP','guild-xp',{amount})).join('')+button('XP bis zum nächsten Gildenlevel','guild-next'))+note(`Aktuell ${s.gold} Gold · ${s.guild.xp} Gilden-XP · Level ${P.guildLevel(s)}. Das Level wird ausschließlich aus XP abgeleitet.`)+grid([1,2,3,4,5].map(level=>button('Gildenlevel '+level,'guild-level',{level})).join(''))+note('Absenken wird abgelehnt, wenn Mitglieder, Gruppen, Einsätze oder gespeicherte Quest-/Poolverträge das höhere Level benötigen.');
  if(tab==='members')return memberSelect()+grid(button('Alle Lebenden +1 Level','members-level')+button('Auswahl +1 Level','member-level',{},!selected.member)+button('Auswahl auf F · Lvl. 10','member-max',{},!selected.member)+button('Alle Verletzungen heilen','members-heal')+button('Alle Lebenden einsatzfähig','members-ready')+button('Auswahl DEV-only wiederherstellen …','member-restore',{},!s.members.some(a=>a.id===selected.member&&a.dead),true))+note('F10 bleibt das Maximum. Einsatzfähig heilt Verletzungen; laufende Quest-/Dungeonbindungen und Combat-HP bleiben bestehen. Wiederherstellen erst nach Einsatzabschluss und Abholung offener Rewards.')+`<h3>Verstorbene</h3><ul>${s.members.filter(a=>a.dead).map(a=>`<li>${esc(a.name)} · F${a.level} · im Register</li>`).join('')||'<li>Keine verstorbenen Mitglieder im Register.</li>'}${s.retiredMembers.map(a=>`<li>${esc(a.name)} · archiviert, nicht wiederherstellbar</li>`).join('')}</ul>`;
  if(tab==='recruit')return `<h3>Kandidaten für Tests</h3>`+note(`Mitgliederlimit: ${s.members.length} / ${P.limits(s).members}. ${s.recruited?'Normale Rekrutierung bleibt kostenpflichtig.':'Zuerst die drei kostenlosen Starter auswählen.'}`)+grid(button('Sofort neuer Pool (kostenlos)','pool-refresh',{},!s.recruited)+button('Neuer F8-Pool · Gildenlevel mindestens 5','pool-high',{},!s.recruited)+[1,5,8].map(level=>button('F'+level+'-Testkandidat im neuen Pool','candidate-add',{level},!s.recruited)).join(''))+note('Jede Testkandidaten-Aktion erzeugt einen neuen 5er-Pool und ersetzt die bisherigen Angebote. F5 setzt mindestens Gildenlevel 4, F8 mindestens 5. F1 verwendet einen gültigen F1-Pool. Es werden keine sechsten Kandidaten oder unbekannten IDs eingefügt.')+grid(button('Mitgliederlimit anzeigen','inspect-capacity')+button('Starterrekrutierung zurücksetzen …','starter-reset',{},false,true));
  if(tab==='items')return `<h3>Vorhandenen Itemkatalog testen</h3>`+grid([0,1,2].map(rarity=>button(P.config.rarityNames[rarity]+'-Testloot','loot-add',{rarity})).join('')+button('+5 Heiltränke','potions-add'))+note('Jedes Lootpaket: vier Klassenwaffen, ein Oberkörperteil und ein Beinteil. Neue eindeutige Item-Instanzen, bestehende Definitionen.')+memberSelect()+grid(button('Rare-Set für Auswahl (3 Items)','rare-set',{},!selected.member)+button('Inventar anzeigen','inventory')+button('Freies Storage leeren …','storage-clear',{},false,true))+note(`Lager: ${s.stock.length} freie Items · ${s.potions} freie Heiltränke. Rare-Set landet im Lager; über normale Ausrüstung/Auto-Equip anlegen. V4.2B zeigt noch das Klassen-Grundoutfit, keine individuellen Itembilder.`);
  if(tab==='quests')return grid(button('Neues Questboard','board-new')+button('Leichtes DEV-Board','board-easy')+button('Starkes dynamisches DEV-Board','board-strong'))+note('Leicht = kleinste gültige Benchmark-Basis des aktuellen Gildenlevels; die vier normalen Schwierigkeitsstufen bleiben bestehen. Stark erhöht nur die DEV-Generierungsbasis. Bestehende Einsatzverträge bleiben unverändert.')+select('quest','Quest',s.quests.map(q=>({id:q.id,label:q.name+' · '+q.status+' · paid='+q.paid})))+partySelect()+grid(button('Alle Timer +60 Sekunden','quest-advance')+button('Alle aktiven Quests auswertungsbereit','quests-ready')+button('Auswahl sofort regulär abschließen','quest-finish',{},!selected.quest)+button('Ergebnis / paid-Status anzeigen','quest-result',{},!selected.quest))+note('Vorspulen verschiebt die gemeinsame Spieluhr: Erholung und laufende Dungeons laufen mit. Sofortabschluss startet ein Angebot mit der gewählten Gruppe, simuliert den normalen Ausgang und zahlt höchstens einmal. Kein garantierter Sieg.');
  if(tab==='dungeon')return D?partySelect()+select('run','Dungeonlauf',D.runs(s).map(d=>({id:d.id,label:d.id+' · Raum '+(d.room+1)+' · '+d.status+' · paid='+d.paid})))+grid(button('Dungeon freischalten (Gildenlevel 2)','dungeon-unlock')+button('Dungeon mit Gruppe sofort starten','dungeon-start',{},!selected.party)+button('Aktuellen Abschnitt vorsimulieren','dungeon-skip',{},!selected.run)+button('Bis Entscheidung simulieren (bei Sieg)','dungeon-decision',{},!selected.run)+button('Dungeon regulär abschließen','dungeon-finish',{},!selected.run)+button('Dungeonstatus anzeigen','dungeon-status')+button('Dungeonstate löschen …','dungeon-clear',{},false,true))+note('Abkürzungen verwenden unverändert den Combat Core. Sie erzwingen weder Sieg noch einen künstlichen Entscheidungspunkt. Niederlage, Tod und technische Abbrüche bleiben möglich. Abschluss läuft durch die bestehenden einmaligen Rewards. Andere Timer laufen mit.'):`<button disabled>Dungeon-System noch nicht verfügbar.</button>`;
  if(tab==='combat'){
   const actors=[...s.members,...s.normalPool,...s.candidates].filter((a,i,all)=>all.findIndex(b=>b.id===a.id)===i);
   return partySelect()+grid(button('Combat-Test starten','combat-test',{},!selected.party)+[1,2,4].map(speed=>button('Probekampf '+speed+'×','combat-speed',{speed},!host.get().combat)).join('')+button('Animations-Test öffnen','animation-test')+button('Walk-Cycle-Test öffnen','walk-test')+button('Reduced Motion: '+(host.get().reducedOverride?'TEST AN':'Systemeinstellung'),'reduced-toggle'))+note('Trainingskampf bleibt ohne Gildenfolgen. Reduced Motion gilt nur in dieser Sitzung; die Systemeinstellung bleibt zusätzlich wirksam.')+(probe?select('actor','Testfigur',actors.map(a=>({id:a.id,label:a.name+' · '+R.classes[a.cls].name})))+select('pose','Testpose',['Idle','Walk','Attack','Cast','Heal','Down'].map(id=>({id,label:id})))+`<div class="admin-stage"><div id="admin-actors" class="adventure-actors"></div></div>`+note('<strong>Basis V4.2B:</strong> Kein V4.2C-Walk-Cycle-Fix vorhanden. Dieser Test zeigt die vorhandene Dreiansichten-/Ganzkörperbewegung, keinen neu erzeugten Gehzyklus.'):'');
  }
  if(tab==='save')return `<h3>Lokaler Spielstand</h3>`+note(esc(saveMessage)+(storage?.paused?' · DEV-Autosave pausiert':''))+grid(button('Spiel speichern','save-current')+button('Spielstand exportieren','save-export')+button('Spielstand importieren','save-import')+button('Autosave-Status anzeigen','save-status')+button('Fortsetzen & aktuellen Stand speichern','save-resume')+button('Backup-Fallback testen (Kopie)','save-fallback')+button('Primary Save löschen …','save-primary-delete',{},false,true)+button('Backup Save löschen …','save-backup-delete',{},false,true)+button('Save beschädigen · TEST-ONLY …','save-corrupt',{},false,true)+button('Neue Gilde starten …','new-guild',{},false,true))+note('Lösch-/Beschädigungstests pausieren Autosave, damit der Testzustand erhalten bleibt. Fortsetzen schreibt den aktuellen Arbeitsspeicherstand ausdrücklich zurück. Reload beendet die Sitzungspause und verwendet den normalen Save-/Backup-Ladeweg. Export funktioniert auch bei pausiertem Autosave.');
  return debug();
 }
 function debug(){const h=host.get(),d=A.inspect(h.state,h.clock,h.storage,h.saveMessage),labels={build:'Build',gold:'Gold',guildXP:'Gilden-XP',guildLevel:'Gildenlevel',members:'Mitglieder / Limit',groups:'Gruppen / Limit',missions:'Einsätze / Limit',activeQuests:'Aktive Quests',pendingQuests:'Pending Quests',paidQuests:'Paid Quests',dungeons:'Aktive Dungeons',saveVersion:'Primary SaveVersion',primary:'Primary',backup:'Backup',autosave:'Autosave',clock:'Spieluhr (ms)'};return `<dl class="admin-inspector">${Object.entries(d).map(([k,v])=>`<div><dt>${labels[k]}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>`+note('Momentaufnahme. Browser: '+esc(typeof navigator==='undefined'?'DOM-Testumgebung':navigator.userAgent))+grid(button('Inspector aktualisieren','inspect')+button('Rohdaten anzeigen','raw'));
 }
 function mountProbe(){scene?.destroy();scene=null;if(!probe||tab!=='combat'||pending)return;scene=new V.Scene();scene.mount($('#admin-actors'));frame(0);}
 function show(){const html=panel();$('#admin-content').innerHTML=html;$('#admin-tabs').innerHTML=tabs.map(([id,label])=>`<button type="button" role="tab" data-action="admin-tab" data-tab="${id}" aria-selected="${tab===id}" class="${tab===id?'active':''}">${label}</button>`).join('');const status=$('#admin-feedback');status.textContent=feedback;status.className=error?'bad':'good';mountProbe();}
 function open(){pending=null;show();if(!dialog.open)dialog.showModal();}
 function close(){pending=null;scene?.destroy();scene=null;probe=null;dialog.close();}
 function tell(message,bad=false){feedback=message;error=bad;host.toast(message);}
 function request(op,args){pending={op,args,token:String(++serial),state:confirmationKey(host.get().state)};scene?.destroy();scene=null;$('#admin-content').innerHTML=`<div class="admin-confirm"><h3>DEV-Aktion bestätigen</h3><p>${esc(reasons[op])}</p><div class="admin-buttons"><button type="button" class="danger" data-action="admin-confirm" data-token="${pending.token}">Jetzt ausdrücklich bestätigen</button><button type="button" class="quiet" data-action="admin-cancel">Abbrechen</button></div></div>`;}
 function execute(op,args,confirmed=false){
  const h=host.get();
  if(op==='inventory'){const eq=h.state.members.flatMap(a=>R.slots.filter(k=>a.gear[k]).map(k=>`${a.name}: ${k} · ${R.item(a.gear[k].def).name}`));$('#admin-content').innerHTML=`<h3>Inventar</h3><p>${h.state.potions} freie Heiltränke · ${h.state.stock.length} freie Items</p><ul>${h.state.stock.map(e=>`<li>${esc(R.item(e.def).name)} · ${esc(e.instance)}</li>`).join('')||'<li>Kein freies Item.</li>'}</ul><h3>Getragen</h3><ul>${eq.map(v=>`<li>${esc(v)}</li>`).join('')||'<li>Keine Ausrüstung angelegt.</li>'}</ul>`;return;}
  if(op==='raw'){$('#admin-content').innerHTML='<h3>Rohdaten · nur lesen</h3><pre class="admin-raw">'+esc(JSON.stringify({clock:h.clock,state:h.state},null,2))+'</pre>';return;}
  if(['inspect','save-status','inspect-capacity','dungeon-status'].includes(op)){tab='debug';show();return;}
  if(op==='quest-result'){const q=h.state.quests.find(q=>q.id===args.quest);if(!q)throw Error('Quest auswählen.');const r=q.result||(q.status==='CompletedPendingResolution'?F.preview(h.state,q.id):null);$('#admin-content').innerHTML=`<h3>${esc(q.name)}</h3><p>${esc(q.status)} · paid=${q.paid}</p>${r?`<p>${q.paid?'Bereits gebucht':q.result?'Ausgewertet, noch nicht bezahlt':'Vorschau, noch nicht ausgewertet/bezahlt'} · ${r.success?'Erfolg':r.wipe?'Wipe':r.retreat?'Rückzug':'Misserfolg'}</p><p>${r.gold} Gold · ${r.guildXP} Gilden-XP</p><ul>${r.members.map(m=>`<li>${esc(h.state.members.find(a=>a.id===m.id)?.name||m.id)}: +${m.xp} XP · ${m.dead?'tot':m.injured?'verletzt':'unversehrt'}</li>`).join('')}</ul>`:'<p>Noch kein Ergebnis bereit.</p>'}`;return;}
  if(op==='animation-test'||op==='walk-test'){probe=op;selected.pose=op==='walk-test'?'Walk':'Idle';probeTime=0;show();return;}
  if(op==='reduced-toggle'){host.setReduced(!h.reducedOverride);tell('Reduced-Motion-Test '+(!h.reducedOverride?'aktiv':'aus; Systemeinstellung gilt'));show();return;}
  if(op==='combat-test'){host.practice(args.party);close();return;}
  if(op==='combat-speed'){host.speed(Number(args.speed));tell('Probekampf '+args.speed+'×');show();return;}
  if(op==='save-export'){host.exportSave();tell('Save-Export vorbereitet');show();return;}
  if(op==='save-import'){close();host.importSave();return;}
  if(op==='save-current'){host.save();tell('Aktueller Spielstand gespeichert');show();return;}
  if(op.startsWith('save-')){const result=A.storageAction(h.storage,h.state,h.clock,op,confirmed);host.storageResult(result);tell(result.message);show();return;}
  const result=A.prepare(h.state,h.clock,op,args,confirmed);if(result.changed)host.commit(result);tell(result.message);show();
 }
 function handle(data){try{
  if(data.action==='admin-close'){close();return;}
  if(data.action==='admin-tab'){pending=null;tab=tabs.some(t=>t[0]===data.tab)?data.tab:'resources';show();return;}
  if(data.action==='admin-cancel'){pending=null;show();return;}
  if(data.action==='admin-confirm'){const p=pending;if(!p||data.token!==p.token)throw Error('Bestätigung fehlt oder wurde bereits verwendet.');pending=null;if(p.state!==confirmationKey(host.get().state))throw Error('Spielstand inzwischen geändert. Aktion erneut öffnen und prüfen.');execute(p.op,p.args,true);return;}
  if(data.action!=='admin-run')return;
  const args={member:selected.member,party:selected.party,quest:selected.quest,run:selected.run,...data};pending=null;
  if(A.dangerous.includes(data.op)){request(data.op,args);return;}execute(data.op,args);
 }catch(e){pending=null;tell(e.message,true);show();}}
 function change(target){const key=target.id?.replace('admin-','');if(Object.hasOwn(selected,key)){selected[key]=target.value;pending=null;show();return true;}return false;}
 function frame(dt){if(!dialog.open||!scene||!probe)return;const h=host.get(),a=[...h.state.members,...h.state.normalPool,...h.state.candidates].find(a=>a.id===selected.actor);if(!a)return;const reduced=host.reduced();if(!reduced)probeTime+=Math.max(0,Math.min(.1,dt));const walking=selected.pose==='Walk',t=(probeTime/5)%2,x=walking&&!reduced?.2+(t<1?t:2-t)*.6:.5;scene.draw([{character:a,x,y:.82,pose:selected.pose,view:walking?'side':'three',facing:t<1?1:-1,label:'DEV · '+selected.pose,life:selected.pose==='Down'?'Incapacitated':'Alive'}],[],dt,reduced);}
 dialog.addEventListener('close',()=>{pending=null;scene?.destroy();scene=null;probe=null;});dialog.addEventListener('cancel',()=>{pending=null;});
 return{open,close,handle,change,frame};
}
g.GuildAdminUI={create,tabs,reasons};
})(typeof globalThis!=='undefined'?globalThis:window);
