/* Authoritative expedition orchestration. Combat rules and normal quest simulation are untouched. */
(function(g){'use strict';
const R=g.GuildRules,P=g.GuildProgression,C=g.GuildCombat,copy=R.clone;
const deepFreeze=o=>{Object.values(o).forEach(v=>{if(v&&typeof v==='object')deepFreeze(v);});return Object.freeze(o);};
const config=deepFreeze({version:'dungeon.goblinmine.v1',unlock:2,recommended:650,
 rooms:[{name:'Die Torwache',enemies:['enemy.goblin.melee','enemy.goblin.ranged'],gold:35,xp:65,guildXP:22,drop:.20,rarities:[.75,.23,.02]},
 {name:'Die Förderstrecke',enemies:['enemy.goblin.melee','enemy.goblin.melee','enemy.goblin.ranged'],gold:45,xp:80,guildXP:28,drop:.25,rarities:[.65,.30,.05]},
 {name:'Der Erzbrecher',enemies:['enemy.goblin.brute','enemy.goblin.brute','enemy.goblin.ranged'],gold:60,xp:105,guildXP:40,drop:.30,rarities:[.45,.45,.10]},
 {name:'Grubenkönig Grak',enemies:['enemy.goblin.boss','enemy.goblin.brute','enemy.goblin.ranged','enemy.goblin.melee'],gold:90,xp:160,guildXP:65,drop:.45,rarities:[.25,.50,.25]}],
 bossBonus:{gold:100,xp:150,guildXP:60},maxRuns:500,maxTicks:520,speeds:[0,1,2,4]});
const active=d=>['Combat','Decision'].includes(d.status),runs=s=>s.expeditions?.runs||[],bound=(s,id)=>runs(s).some(d=>active(d)&&d.participants.includes(id)),partyBound=(s,id)=>runs(s).some(d=>active(d)&&d.party===id),count=s=>runs(s).filter(active).length;
const original={change:R.change,initial:R.initial,locked:R.locked,partyLocked:R.partyLocked,validate:R.validate,equip:R.equip};
const missions=s=>count(s)+s.quests.filter(q=>['Active','CompletedPendingResolution'].includes(q.status)).length;
function empty(){return{sequence:0,portalAnnounced:false,runs:[]};}
const runId=n=>'browser.dungeon.'+String(n).padStart(8,'0'),seed=(id,room)=>BigInt('0x'+R.hash(config.version,id,String(room),'combat').slice(0,16)).toString();
function pack(c,inputs,seedValue){return{inputs:copy(inputs),seed:seedValue,state:copy(c.state),pending:c.terminal?0:c.pending,speed:c.speed};}
function revive(x){const c=new C.Combat(x.inputs,BigInt(x.seed));c.state=copy(x.state);c.pending=x.pending;c.speed=x.speed;return c;}
function partyStates(d){const map=new Map(d.encounters[0]?.combat.inputs.filter(a=>a.source).map(a=>[a.source,{id:a.source,life:'Alive',hp:a.hp,mana:R.profiles[a.def].mana,recovery:0}])||d.current?.inputs.filter(a=>a.source).map(a=>[a.source,{id:a.source,life:'Alive',hp:a.hp,mana:R.profiles[a.def].mana,recovery:0}])||[]);
 for(const x of [...d.encounters.map(e=>e.combat),...(d.current?[d.current]:[])])for(const a of x.state.members.filter(a=>a.faction==='Adventurer'))map.set(a.source,{id:a.source,life:a.life,hp:a.hp,mana:a.mana,recovery:a.wasIncap&&a.life!=='Dead'?120:0});return [...map.values()];}
function roomInputs(s,d){const previous=new Map(partyStates(d).map(a=>[a.id,a]));const out=d.participants.filter(id=>!previous.size||previous.get(id)?.life==='Alive').map(id=>{const a=s.members.find(a=>a.id===id);return C.input(a.id,a.cls,a.id,R.slots.map(k=>a.gear[k]),previous.get(id)?.hp);});
 config.rooms[d.room].enemies.forEach((def,i)=>out.push(C.input(d.id+'.r'+d.room+'.enemy.'+i,def)));return out;}
function begin(s,d,now){const inputs=roomInputs(s,d),value=seed(d.id,d.room),c=new C.Combat(inputs,BigInt(value));d.current=pack(c,inputs,value);d.status='Combat';d.lastTime=now;}
function mergeLoot(a,b){const map=new Map();for(const l of [...a,...b])map.set(l.def,(map.get(l.def)||0)+l.qty);return [...map].sort(([a],[b])=>R.cmp(a,b)).map(([def,qty])=>({def,qty}));}
function roomReward(id,index){const r=config.rooms[index],u=domain=>parseInt(R.hash(config.version,id,String(index),'loot',domain).slice(0,8),16)/4294967296;return{gold:r.gold,xp:r.xp,guildXP:r.guildXP,loot:P.loot({tier:'easy',dynamic:r},u)};}
function expectedSecured(d){const total={gold:0,xp:0,guildXP:0,loot:[]};for(const e of d.encounters)if(e.combat.state.result?.outcome==='Victory'){const reward=roomReward(d.id,e.room);for(const k of ['gold','xp','guildXP'])total[k]+=reward[k];total.loot=mergeLoot(total.loot,reward.loot);}if(d.status==='Completed'){for(const k of ['gold','xp','guildXP'])total[k]+=config.bossBonus[k];const rares=R.items.filter(a=>a.slot&&a.rarity===2),it=rares[parseInt(R.hash(config.version,d.id,'boss-loot').slice(0,8),16)%rares.length];total.loot=mergeLoot(total.loot,[{def:it.id,qty:1}]);}return total;}
function project(s,d,endedAt){for(const m of partyStates(d)){const a=s.members.find(a=>a.id===m.id);if(!a)throw Error('Dungeonmitglied fehlt');if(m.life==='Dead'&&!a.dead){a.dead=true;a.recovery=0;s.potions+=a.potion;a.potion=0;for(const k of R.slots){if(a.gear[k])s.stock.push(a.gear[k]);a.gear[k]=null;}}else if(m.recovery&&!a.dead)a.recovery=Math.max(a.recovery,endedAt+m.recovery*1000);}}
function finish(d,status,at){d.status=status;d.finishedAt=at;d.secured=expectedSecured(d);d.reward=copy(d.secured);}
function settle(s,d,at){const c=d.current;d.encounters.push({room:d.room,endedAt:at,combat:c});d.current=null;const result=c.state.result;project(s,d,at);
 if(c.state.phase==='TechnicalAbort')finish(d,'TechnicalAbort',at);
 else if(result.outcome!=='Victory')finish(d,result.wipe?'Wipe':'Defeat',at);
 else if(d.room===config.rooms.length-1)finish(d,'Completed',at);
 else{d.status='Decision';d.secured=expectedSecured(d);}d.lastTime=at;}
function advance(state,now,onFrame=null){if(!Number.isFinite(now)||now<0)throw Error('Ungültige Dungeonzeit');let s=state;
 for(const old of runs(state)){if(old.status!=='Combat'||!old.current.speed||now<=old.lastTime)continue;if(s===state)s=copy(state);const d=s.expeditions.runs.find(x=>x.id===old.id),c=revive(d.current),before=c.state.tick,pending=c.pending,speed=c.speed;c.advance(now-d.lastTime);if(onFrame)onFrame(d.id,c.state,c.log.filter(e=>e.tick>before),speed);const at=c.terminal?d.lastTime+Math.max(0,((c.state.tick-before)*250-pending)/speed):now;d.current=pack(c,d.current.inputs,d.current.seed);d.lastTime=now;if(c.terminal)settle(s,d,at);}
 return s;
}
function checkStart(s,party,now){if(P.guildLevel(s)<config.unlock)throw Error('Dungeon: Gilden-Lvl. 2 erforderlich.');const p=s.parties.find(p=>p.id===party);if(!p||!p.members.length||p.members.length>6)throw Error('Gültige Gruppe wählen.');if(R.partyLocked(s,p.id)||p.members.some(id=>{const a=s.members.find(a=>a.id===id);return !a||!R.available(a,now)||R.locked(s,id);}))throw Error('Gruppe ist gebunden oder nicht einsatzfähig.');if(missions(s)>=P.limits(s).missions)throw Error('Alle verfügbaren Einsatzplätze sind belegt.');if(runs(s).some(d=>!active(d)&&!d.paid&&d.participants.some(id=>p.members.includes(id))))throw Error('Zuerst offene Dungeonbelohnung übernehmen.');if(runs(s).length>=config.maxRuns)throw Error('Dungeonhistorie ist voll. Spielstand exportieren.');return p;}
function change(state,op,args={},now=1000){let s=state;if(op.startsWith('dungeon-')){if(op==='dungeon-start'){const p=checkStart(state,args.party,now);s=copy(state);s.expeditions??=empty();original.equip(s,p.members);const d={id:runId(++s.expeditions.sequence),def:config.version,party:p.id,participants:p.members.slice(),leader:p.leader,start:now,lastTime:now,room:0,status:'Combat',encounters:[],current:null,secured:{gold:0,xp:0,guildXP:0,loot:[]},reward:null,paid:false,finishedAt:null};begin(s,d,now);s.expeditions.runs.push(d);}
 else{const old=runs(state).find(d=>d.id===args.id);if(!old)throw Error('Dungeon nicht gefunden.');if(op==='dungeon-claim'&&old.paid)return state;s=copy(state);const d=s.expeditions.runs.find(d=>d.id===args.id);
 if(op==='dungeon-speed'){if(d.status!=='Combat'||!config.speeds.includes(args.speed))throw Error('Ungültige Kampfgeschwindigkeit.');s=advance(s,now);const run=s.expeditions.runs.find(d=>d.id===args.id);if(run.status==='Combat'){run.current.speed=args.speed;run.lastTime=now;}}
 else if(op==='dungeon-next'){if(d.status!=='Decision'||args.room!==d.room)throw Error('Entscheidung wurde bereits verarbeitet.');d.room++;begin(s,d,now);}
 else if(op==='dungeon-retreat'){if(d.status!=='Decision'||args.room!==d.room)throw Error('Rückzug nur zwischen Encountern.');finish(d,'Retreated',now);}
 else if(op==='dungeon-claim'){if(active(d)||!d.reward)throw Error('Dungeon noch nicht beendet.');const rewards=d.reward;s.gold+=rewards.gold;s.guild.xp=Math.min(1000,s.guild.xp+rewards.guildXP);for(const id of d.participants){const a=s.members.find(a=>a.id===id);if(!a)throw Error('Rewardempfänger fehlt');if(!a.dead){a.xp=Math.min(630,a.xp+Math.floor(rewards.xp/d.participants.length));a.level=R.level(a.xp);}}for(const l of rewards.loot){if(!R.item(l.def).slot)s.potions+=l.qty;else for(let i=0;i<l.qty;i++)s.stock.push({def:l.def,instance:'browser.item.'+String(++s.itemSeq).padStart(8,'0')});}d.paid=true;}
 else throw Error('Unbekannte Dungeonaktion.');}
 }else{
 if(op==='start'){if(missions(state)>=P.limits(state).missions)throw Error('Alle verfügbaren Einsatzplätze sind belegt.');const p=state.parties.find(p=>p.id===args.party);if(p&&(partyBound(state,p.id)||p.members.some(id=>bound(state,id))))throw Error('Gruppe ist im Dungeon gebunden.');}
 if(['leader','clearLeader','remove','add','transfer','dissolve'].includes(op)&&(partyBound(state,args.party)||partyBound(state,args.to)))throw Error('Dungeon-Gruppe ist gebunden.');
 if(['return','equipItem','removeDead','add','transfer','leader'].includes(op)&&bound(state,args.member))throw Error('Dungeon-Mitglied ist gebunden.');
 if(op==='removeDead'&&runs(state).some(d=>!d.paid&&d.participants.includes(args.member)))throw Error('Zuerst offene Dungeonbelohnung übernehmen.');
 if(op==='createParty'&&args.ids?.some(id=>bound(state,id)))throw Error('Dungeon-Mitglied ist gebunden.');
 if(op==='equip'){s=copy(state);original.equip(s,s.members.filter(a=>!a.dead&&!R.locked(s,a.id)).map(a=>a.id));}else s=original.change(state,op,args,now);
 }
 if(s!==state){if(s.expeditions&&!s.expeditions.portalAnnounced&&P.guildLevel(s)>=2)s.expeditions.portalAnnounced=true;R.validate(s);P.validate(s);validate(s,false);}return s;
}
function validate(s,deep=false){const e=s.expeditions;if(!e)return true;
 const fail=()=>{throw Error('Ungültiger Dungeon-Spielstand');},integer=(v,min=0,max=Number.MAX_SAFE_INTEGER)=>{if(!Number.isSafeInteger(v)||v<min||v>max)fail();},time=v=>{if(!Number.isFinite(v)||v<0||v>1e15)fail();},shape=(o,ks)=>{if(!o||typeof o!=='object'||Array.isArray(o)||Object.keys(o).sort().join('|')!==ks.slice().sort().join('|'))fail();};
 shape(e,['sequence','portalAnnounced','runs']);integer(e.sequence,0,config.maxRuns);if(typeof e.portalAnnounced!=='boolean'||!Array.isArray(e.runs)||e.runs.length!==e.sequence)fail();if(missions(s)>P.limits(s).missions)fail();const allIds=new Set([...s.members,...s.retiredMembers].map(a=>a.id)),locks=new Set(),parties=new Set();
 for(let i=0;i<e.runs.length;i++){const d=e.runs[i];shape(d,['id','def','party','participants','leader','start','lastTime','room','status','encounters','current','secured','reward','paid','finishedAt']);if(d.id!==runId(i+1)||d.def!==config.version||!['Combat','Decision','Completed','Retreated','Defeat','Wipe','TechnicalAbort'].includes(d.status)||typeof d.paid!=='boolean')fail();time(d.start);time(d.lastTime);if(d.lastTime<d.start)fail();integer(d.room,0,3);if(!Array.isArray(d.participants)||d.participants.length<1||d.participants.length>6||new Set(d.participants).size!==d.participants.length||d.participants.some(id=>!allIds.has(id))||(d.leader!==null&&!d.participants.includes(d.leader)))fail();
 if(!Array.isArray(d.encounters)||d.encounters.length>4||(d.status==='Combat'?d.encounters.length!==d.room:d.encounters.length!==d.room+1))fail();
 if(active(d)){if(d.paid||d.reward!==null||d.finishedAt!==null||P.guildLevel(s)<2)fail();const p=s.parties.find(p=>p.id===d.party);if(!p||JSON.stringify(p.members)!==JSON.stringify(d.participants)||p.leader!==d.leader||original.partyLocked(s,p.id)||parties.has(p.id))fail();parties.add(p.id);for(const id of d.participants){if(locks.has(id)||original.locked(s,id))fail();locks.add(id);}}
 else{time(d.finishedAt);if(d.finishedAt<d.start||!d.reward||JSON.stringify(d.reward)!==JSON.stringify(d.secured))fail();if(!d.paid&&d.participants.some(id=>!s.members.some(a=>a.id===id)))fail();}
 const history=[...d.encounters.map((v,j)=>{shape(v,['room','endedAt','combat']);if(v.room!==j)fail();time(v.endedAt);if(v.endedAt<d.start||v.endedAt>d.lastTime)fail();return v.combat;}),...(d.current?[d.current]:[])];
 if((d.status==='Combat')!==Boolean(d.current))fail();
 for(let j=0;j<history.length;j++){const c=history[j];shape(c,['inputs','seed','state','pending','speed']);if(c.seed!==seed(d.id,j)||!config.speeds.includes(c.speed)||!Number.isFinite(c.pending)||c.pending<0||c.pending>=250)fail();integer(c.state?.tick,0,config.maxTicks);if(!Array.isArray(c.inputs)||c.inputs.length<2||c.inputs.length>12)fail();for(const input of c.inputs){shape(input,['id','def','source','gear','hp']);if(!Array.isArray(input.gear)||input.gear.length!==3)fail();for(const gear of input.gear)if(gear!==null)shape(gear,['def','instance']);}const enemies=c.inputs.filter(a=>!a.source);if(JSON.stringify(enemies.map(a=>a.def))!==JSON.stringify(config.rooms[j].enemies)||enemies.some((a,k)=>a.id!==d.id+'.r'+j+'.enemy.'+k))fail();const allies=c.inputs.filter(a=>a.source);if(allies.some(a=>{const source=[...s.members,...s.retiredMembers].find(m=>m.id===a.source);return !source||a.def!==source.cls||!d.participants.includes(a.source)||a.id!==a.source||(j===0&&a.hp!==R.profiles[a.def].hp);}))fail();if(j===0&&JSON.stringify(allies.map(a=>a.source))!==JSON.stringify(d.participants))fail();if(j>0){const prev=history[j-1].state.members.filter(a=>a.faction==='Adventurer'&&a.life==='Alive');if(allies.length!==prev.length||allies.some(a=>{const m=prev.find(m=>m.source===a.source);return !m||m.def!==a.def||m.hp!==a.hp||JSON.stringify(m.gear)!==JSON.stringify(a.gear);}))fail();}
 if(j<d.encounters.length&&!['Completed','TechnicalAbort'].includes(c.state.phase))fail();if(j<d.encounters.length-1&&c.state.result?.outcome!=='Victory')fail();if(deep)validateCombat(c,fail);
 }
 if(JSON.stringify(d.secured)!==JSON.stringify(expectedSecured(d)))fail();const last=history.at(-1)?.state;
 if(d.status==='Decision'&&(last?.result?.outcome!=='Victory'||d.room>=3))fail();if(d.status==='Completed'&&(d.room!==3||last?.result?.outcome!=='Victory'))fail();if(d.status==='Retreated'&&(d.room>=3||last?.result?.outcome!=='Victory'))fail();if(['Defeat','Wipe'].includes(d.status)&&(last?.result?.outcome!=='Defeat'||last.result.wipe!==(d.status==='Wipe')))fail();if(d.status==='TechnicalAbort'&&last?.phase!=='TechnicalAbort')fail();if(d.status==='Combat'&&['Completed','TechnicalAbort'].includes(last?.phase))fail();
 if(active(d)||!d.paid)for(const m of partyStates(d)){const a=s.members.find(a=>a.id===m.id);if(!a||(active(d)&&m.life==='Alive'&&a.dead)||(m.life==='Dead'&&d.status!=='Combat'&&!a.dead))fail();if(m.life==='Alive'&&d.status==='Combat'){const input=d.current.inputs.find(x=>x.source===m.id);if(input&&JSON.stringify(input.gear)!==JSON.stringify(R.slots.map(k=>a.gear[k])))fail();}}
 }
 return true;
}
const validationCache=new Set();function validateCombat(c,fail){const key=JSON.stringify(c);if(validationCache.has(key))return;let sim;try{sim=new C.Combat(c.inputs,BigInt(c.seed));while(sim.state.tick<c.state.tick&&!sim.terminal)sim.step();}catch(_){fail();}if(JSON.stringify(sim.state)!==JSON.stringify(c.state))fail();validationCache.add(key);if(validationCache.size>64)validationCache.delete(validationCache.values().next().value);}
R.initial=()=>{const s=original.initial();s.expeditions=empty();return s;};R.change=change;R.locked=(s,id)=>original.locked(s,id)||bound(s,id);R.partyLocked=(s,id)=>original.partyLocked(s,id)||partyBound(s,id);
R.validate=s=>{original.validate(s);if(missions(s)>P.limits(s).missions)throw Error('Alle verfügbaren Einsatzplätze sind belegt.');return true;};
const previewStart=P.previewStart;P.previewStart=(s,q,p,now=1000)=>{if(partyBound(s,p))throw Error('Gruppe ist im Dungeon gebunden.');if(missions(s)>=P.limits(s).missions)throw Error('Alle verfügbaren Einsatzplätze sind belegt.');return previewStart(s,q,p,now);};
g.GuildDungeon={config,empty,active,runs,bound,partyBound,count,missions,checkStart,partyStates,roomReward,expectedSecured,advance,revive,validate,original};if(typeof module!=='undefined')module.exports=g.GuildDungeon;
})(typeof globalThis!=='undefined'?globalThis:window);
