/* Browser presentation and in-memory service composition, separate from the Unity project. */
(()=>{'use strict';const R=GuildRules,C=GuildCombat,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const P=typeof GuildProgression!=='undefined'?GuildProgression:null;
const D=typeof GuildDungeon!=='undefined'?GuildDungeon:null,CP=typeof GuildCharacterPresentation!=='undefined'?GuildCharacterPresentation:null,XP=typeof GuildExpeditionPresentation!=='undefined'?GuildExpeditionPresentation:null,AH=typeof GuildAdventureHall!=='undefined'?GuildAdventureHall:null;
const expeditionView=XP?new XP.View():null;let watched={type:'quest',id:''},journeySpeed=1,pendingWatch=null,lastDungeonSave=0;
const F=typeof GuildAdventureFlow!=='undefined'?GuildAdventureFlow:null;
const N=typeof GuildRecruitment!=='undefined'?GuildRecruitment:null,S=typeof GuildSave!=='undefined'?GuildSave:null;
let store=null,saveMessage='Noch nicht gespeichert',saveError=false,resetArmed=false;
let state=R.initial(),page='hall',selection=new Set(),draft=new Set(),party='',showPaid=false,combat=null,clock=1000,previous=performance.now(),toastTimer,recruitBusyUntil=0,recentQuest='',shownGold=null;
if(S){try{store=S.createStore(window.localStorage);const saved=store.loadGame();if(saved.kind==='primary'||saved.kind==='backup'){state=saved.state;clock=saved.clock;saveMessage=saved.kind==='backup'?saved.message:'Lokalen Spielstand geladen';}else if(saved.kind==='corrupt'){saveMessage=saved.message;saveError=true;}}catch(e){saveMessage=e.message;saveError=true;}}
const hallModel=AH?new AH.LeaderHall():typeof GuildHall!=='undefined'?new GuildHall.HallModel():null;
const hallView=hallModel&&typeof GuildHallView!=='undefined'?new (AH?AH.LeaderHallView:GuildHallView.HallView)(hallModel,id=>{go('roster');toast((member(id)?.name||'Mitglied')+' · Profil geöffnet');const card=document.querySelector('[data-roster-member="'+id+'"]');card?.scrollIntoView?.({block:'nearest',behavior:reduced()?'instant':'smooth'});}):null;
let previousHallFrame=0,lastHallDraw=0,hadDepartures=false;
function syncHall(){hallModel?.sync(state,clock);}
function mountHall(){hallView?.mount(page==='hall'?document.querySelector('#hall-residents'):null);hallView?.draw();}
function hallFrame(time){const dt=previousHallFrame?Math.min((time-previousHallFrame)/1000,.1):0;previousHallFrame=time;if(!document.hidden&&hallModel){hallModel.update(dt,reduced());if(page==='hall'&&(AH||time-lastHallDraw>=1000/30)){hallView?.draw();lastHallDraw=time;}const leaving=hallModel.snapshot().some(a=>a.departing);if(hadDepartures&&!leaving){if(page==='quests')render();if(page==='hall')toast('Die Gruppe ist aufgebrochen. Das Questbrett zeigt ihren Fortschritt.');}hadDepartures=leaving;if(pendingWatch&&!leaving){const next=pendingWatch;pendingWatch=null;watchExpedition(next.type,next.id);}}updateExpedition(dt);requestAnimationFrame(hallFrame);}
const pages=[['hall','⌂','Halle'],['recruit','✦','Rekrutierung'],['roster','♙','Mitglieder'],['party','⚑','Gruppen'],['quests','▤','Quests'],['storage','▣','Lager'],['combat','⚔','Probekampf']];
const btn=(label,action,data={},disabled=false,kind='')=>`<button class="${kind}" data-action="${action}" ${Object.entries(data).map(([k,v])=>`data-${k}="${esc(v)}"`).join(' ')} ${disabled?'disabled':''}>${label}</button>`;
const member=id=>state.members.find(a=>a.id===id)||state.retiredMembers.find(a=>a.id===id),pname=id=>state.parties.find(p=>p.id===id)?.name||'Keine Gruppe',current=()=>state.parties.find(p=>p.id===party),status=a=>a.dead?'Tot':a.recovery>clock?`Verletzt · ${Math.ceil((a.recovery-clock)/1000)}s`:'Einsatzfähig';
const cls=a=>R.classes[a.cls],title=(n,text='',action='')=>`<div class="page-title"><div><div class="eyebrow">DIE GILDE · ABENTEUER BEGINNEN HIER</div><h1>${n}</h1><p>${text}</p></div>${action}</div>`;
const portrait=a=>CP?`<div class="portrait shared-portrait ${F?'quality-portrait':''}"><div class="figure-art">${CP.markup(a)}</div></div>`:`<div class="portrait ${a.dead?'portrait-dead':a.recovery>clock?'portrait-injured':''}" style="--class:${cls(a).color}"><span class="painted-full class-rig-${['class.warrior','class.rogue','class.mage','class.priest'].indexOf(a.cls)}" role="img" aria-label="${cls(a).name}"></span>${a.dead?'<span class="portrait-status">Verstorben</span>':a.recovery>clock?'<span class="portrait-status">Verletzt</span>':''}</div>`;
const art=def=>'assets/'+(def.startsWith('enemy.')?'goblin-'+def.split('.').at(-1):def.split('.')[1])+'.svg';
const lifeName={Alive:'Kampfbereit',Incapacitated:'Kampfunfähig',Stabilized:'Stabilisiert',Dead:'Gefallen'};
const reduced=()=>typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches;
function moment(kind,text){const box=$('#moment');if(!box)return;box.className='moment '+kind;box.textContent=text;box.hidden=false;clearTimeout(moment.timer);moment.timer=setTimeout(()=>box.hidden=true,3000);}
function lockRecruit(){recruitBusyUntil=performance.now()+500;setTimeout(()=>{if(page==='recruit')render();},510);}
const badge=t=>`<span class="badge">${esc(t)}</span>`;
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',4200);}
function go(target){if(page==='combat'&&target!=='combat'&&combat)combat.speed=0;if(XP)expeditionView.mount(null,'');page=target;render();$('#content').scrollTop=0;}
function resources(){if(P)return resourcesV4();const gold=state.gold;if(shownGold!==gold){const delta=shownGold===null?0:gold-shownGold;$('#resources').innerHTML=`<span class="gold-resource ${delta?'resource-flash':''}"><i class="coin">G</i><b>${gold}</b><small>Gold</small>${delta?`<em class="resource-change ${delta<0?'spend':''}">${delta>0?'+':''}${delta}</em>`:''}</span><span><b>${state.members.length}/12</b><small>Mitglieder</small></span><span><b>${(D?D.missions(state):state.quests.filter(q=>['Active','CompletedPendingResolution'].includes(q.status)).length)}/3</b><small>Einsätze</small></span>`;shownGold=gold;}else{const nodes=$('#resources').querySelectorAll?$('#resources').querySelectorAll('span > b'):[];if(nodes[1])nodes[1].textContent=state.members.length+'/12';if(nodes[2])nodes[2].textContent=(D?D.missions(state):state.quests.filter(q=>['Active','CompletedPendingResolution'].includes(q.status)).length)+'/3';}}
function picker(){if(!state.parties.length)return`<div class="notice">Erst eine Gruppe zusammenstellen. ${btn('Zu den Gruppen','nav',{page:'party'})}</div>`;if(!current())party=state.parties[0].id;return`<div class="pill-row">${state.parties.map(p=>btn(`${esc(p.name)} · ${p.members.length}${R.partyLocked(state,p.id)?' 🔒':''}`,'pick',{id:p.id},false,p.id===party?'active':'quiet')).join('')}</div>`;}
function recruitCost(a){return N?N.price(a):R.recruitmentConfig.candidateCost;}
function levelProgress(a){if(a.level===10)return 'XP 630 / 630 · Maximales F-Level';const floor=R.thresholds[a.level-1],target=R.thresholds[a.level];return `XP ${a.xp-floor} / ${target-floor} · noch ${target-a.xp} bis Lvl. ${a.level+1}`;}
function memberFacts(a){return `Rang ${esc(a.rank||'F')} · Lvl. ${a.level} · STÄRKE ${P?P.power(a):0}<br>${cls(a).role} · ${status(a)}${R.locked(state,a.id)?D?.bound(state,a.id)?' · Dungeongebunden':' · Questgebunden':''}`;}
function partyFacts(p){const ms=p.members.map(member),roles=ms.filter(a=>R.available(a,clock)).reduce((r,a)=>r|cls(a).roles,0);return `<div class="party-summary"><b>GRUPPENSTÄRKE ${P.partyPower(state,p,clock)} · Ø Level ${(ms.reduce((n,a)=>n+a.level,0)/ms.length).toFixed(1).replace('.',',')}</b><p>${['Tank','Schaden','Heilung','Support/Control'].map((n,i)=>`${n} ${roles&(1<<i)?'✓':'—'}`).join(' · ')}</p><small>Rollenabdeckung: lebende, genesene Mitglieder. Durchschnitt: gesamte Gruppe.</small></div>`;}
function saveIndicator(message,error=false){saveMessage=message;saveError=error;const el=document.querySelector('#save-state');if(el){el.textContent=message;el.className=error?'bad':'muted';}}
function autosave(){if(!S)return;try{if(!store)throw Error('Lokaler Speicher nicht verfügbar. Export sichern.');store.saveGame(state,clock);saveIndicator('Lokal gespeichert');}catch(e){saveIndicator(e.message,true);toast(e.message);}}
function resetPresentation(){pendingWatch=null;if(XP){expeditionView.mount(null,'');expeditionView.returnTimes.clear();}combat=null;party='';selection.clear();draft.clear();showPaid=false;shownGold=null;resourcesV4.stamp=null;recruitBusyUntil=0;previous=performance.now();if(hallModel){hallModel.actors.clear();hallModel.memberIds.clear();hallModel.questStatus.clear();hallModel.initialized=false;}}
function exportCurrent(){const text=JSON.stringify(S.createSaveData(state,clock),null,2),url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='GuildGame_Save_'+new Date().toISOString().slice(0,10)+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('JSON-Export vorbereitet. Datei im Browser sichern.');}
async function importSelected(file){if(!file)return;try{if(file.size>S.MAX_BYTES)throw Error('Import maximal 2 MiB.');if(!store)throw Error('Lokaler Speicher nicht verfügbar; aktueller Stand unverändert.');const imported=store.importSave(await file.text());state=imported.state;clock=imported.clock;resetPresentation();saveIndicator('Import validiert und lokal gespeichert');$('#dialog').close();if(F)resumeAdventure();else go('hall');toast('Spielstand vollständig importiert.');}catch(e){saveIndicator(e.message,true);toast('Import abgelehnt: '+e.message);}finally{const input=$('#save-import');if(input)input.value='';}}

function signed(n){return n>0?'+'+n+' ↑':n<0?n+' ↓':'±0 →';}
function deltaLine(label,before,after){return `<div class="list-row"><span>${label}</span><b class="${after>before?'good':after<before?'bad':'muted'}">${before} → ${after} (${signed(after-before)})</b></div>`;}
function unlocks(n){return n?[n.extraGroups?'+'+n.extraGroups+' Gruppenplatz':'',n.extraMembers?'+'+n.extraMembers+' Mitgliederkapazität':'',n.extraMissions?'+'+n.extraMissions+' Einsatzplatz':''].filter(Boolean).join(' · '):'Alle Playtest-Freischaltungen erreicht';}
function resourcesV4(){const l=P.limits(state),n=P.next(state),delta=shownGold===null?0:state.gold-shownGold;const stamp=[state.gold,state.members.length,state.parties.length,state.guild.xp,(D?D.missions(state):state.quests.filter(q=>['Active','CompletedPendingResolution'].includes(q.status)).length)].join('|');if(resourcesV4.stamp===stamp)return;resourcesV4.stamp=stamp;shownGold=state.gold;$('#resources').innerHTML=`<button class="guild-chip quiet" data-action="guild-info"><b>Gilden-Lvl. ${l.level}</b><small>${state.guild.xp} / ${n?n.xp:P.config.guild.at(-1).xp} Gilden-XP</small></button><span class="gold-resource ${delta?'resource-flash':''}"><i class="coin">G</i><b>${state.gold}</b><small>Gold</small>${delta?`<em class="resource-change">${delta>0?'+':''}${delta}</em>`:''}</span><span><b>${state.members.length}/${l.members}</b><small>Mitglieder</small></span><span><b>${state.parties.length}/${l.groups}</b><small>Gruppen</small></span><span><b>${(D?D.missions(state):state.quests.filter(q=>['Active','CompletedPendingResolution'].includes(q.status)).length)}/${l.missions}</b><small>Einsätze</small></span>`;}
function guildDetails(){const l=P.limits(state),n=P.next(state);return `<h2>Gilden-Lvl. ${l.level}</h2><p>${state.guild.xp} kumulative Gilden-XP${n?' · Noch '+n.remaining+' bis Lvl. '+n.level:' · Playtest-Maximum erreicht'}</p><div class="progress xp"><i style="width:${n?(state.guild.xp-l.xp)/(n.xp-l.xp)*100:100}%"></i></div><h3>Nächste Freischaltung</h3><p>${unlocks(n)}</p>${P.config.guild.map((v,i)=>`<div class="list-row"><span>${i+1<=l.level?'✓':'🔒'} Gilden-Lvl. ${i+1} · ${v.xp} XP</span><b>${v.members} Mitglieder · ${v.groups} Gruppen · ${v.missions} Einsätze</b></div>`).join('')}<p class="footer-note">Gilden-XP nur aus erfolgreichen Quests, atomar mit der einmaligen Belohnungsübernahme. Lokaler Spielstand.</p>`;}
function groupSlots(){const l=P.limits(state),n=P.next(state);return `<div class="guild-progression"><div class="row spread"><b>Gilden-Lvl. ${l.level} · ${state.guild.xp} Gilden-XP</b>${btn('Freischaltungen','guild-info',{},false,'quiet')}</div><p>${n?'Noch '+n.remaining+' Gilden-XP · '+unlocks(n):unlocks(null)}</p><div class="slot-strip">${P.config.guild.map((v,i)=>`<span class="badge ${i>=l.groups?'locked-slot':''}">${i<state.parties.length?'✓ Gruppe belegt':i<l.groups?'＋ Gruppenplatz frei':'🔒 Gilden-Lvl. '+(i+1)}</span>`).join('')}</div></div>`;}
function questFacts(q){const t=P.tier(q),assigned=F&&q.party?state.parties.find(p=>p.id===q.party):current(),strength=F&&q.result?q.result.power:P.partyPower(state,assigned,clock),risk=P.risk(strength,q.recommended);return `<div class="quest-tier tier-${t.id}">${t.name.toUpperCase()} ${'★'.repeat(t.stars)}</div><div class="power-comparison"><span>Empfohlen <b>${q.recommended}</b></span><span>Deine Gruppe <b>${strength}</b></span></div><p class="${risk.warn?'bad':'good'}">${risk.label.toUpperCase()} · ${signed(risk.delta)}</p><small>Rang F · ${Math.round(q.duration/1000)} Sekunden<br>${q.dynamic?'Board '+q.dynamic.generationSequence+' · Basis '+q.dynamic.benchmarkPower+' Stärke · eingefroren<br>':'V4.1A-Angebot · unverändert<br>'}${q.gold} Gold · ${q.xp} Gruppen-XP · ${t.guildXP} Gilden-XP bei Erfolg<br>${Math.round(t.drop*100)} % Beutechance je Itemfamilie · Common / Uncommon / Rare ${t.rarities.map(n=>Math.round(n*100)+' %').join(' / ')}</small>`;}
function questsV4(){return title('Wähle deine Herausforderung.','Questwerte bleiben bis zu neuen Angeboten fest. Ausrüstung und Level verbessern deine Chancen. Die Risikoprognose ist keine Erfolgsgarantie.')+picker()+groupSlots()+`<div class="row spread">${btn(showPaid?'Abgeholte ausblenden':'Abgeholte anzeigen','show-paid',{},false,'quiet')}</div><div class="grid">${state.quests.filter(q=>showPaid||!q.paid).map(q=>`<article class="card quest-card"><div class="row spread"><span>${typeNames[q.type]} · ${q.distance}</span>${badge(q.status==='Available'?'Verfügbar':q.status==='Active'?'Unterwegs':q.status==='CompletedPendingResolution'?'Auswertungsbereit':'Ausgewertet')}</div><h3>${esc(q.name)}</h3>${questFacts(q)}${XP&&q.status!=='Available'?btn('Abenteuer ansehen','expedition-open',{type:'quest',id:q.id},false,'quiet full'):''}${q.status==='Available'?`<footer>${btn('Mit Gruppe starten','start',{quest:q.id},!current(),'primary full')}</footer>`:q.status==='Active'&&hallModel?.snapshot().some(a=>a.departing&&q.participants.includes(a.id))?'<p>Die Gruppe sammelt sich und bricht auf …</p>':q.status==='Active'?`<div class="progress"><i data-progress="${q.id}" style="width:${Math.min(100,(clock-q.start)/q.duration*100)}%"></i></div><p data-countdown="${q.id}">${Math.max(0,Math.ceil((q.end-clock)/1000))}s verbleibend</p>`:q.status==='CompletedPendingResolution'?(F?btn('Ergebnis ansehen & abschließen','complete-from-hall',{type:'quest',id:q.id},false,'primary full'):btn('Ergebnis auswerten','resolve',{quest:q.id},false,'primary full')):result(q)}</article>`).join('')}</div><div class="selection-bar row spread"><span>Neue Angebote verwenden deinen aktuellen Kaderfortschritt. Laufende Quests bleiben erhalten.</span>${btn('Neue Angebote','offers',{},false)}</div>`;}
function comparisonDialog(instance,target){const e=state.stock.find(e=>e.instance===instance);if(!e)throw Error('Item nicht mehr im Lager');const it=R.item(e.def),a=state.members.find(a=>a.id===target)||state.members.find(a=>!a.dead&&it.allowed.includes(a.cls))||state.members[0];if(!a){modal('<h2>Zuerst Gefährten rekrutieren</h2>');return;}const c=P.compare(a,e);modal(`<h2>${esc(it.name)}</h2><p>${P.config.rarityNames[it.rarity]} · ${it.slot} · Verkaufswert ${c.sell} Gold</p><div class="pill-row">${state.members.map(m=>btn(esc(m.name),'compare-target',{instance,member:m.id},false,m.id===a.id?'active':'quiet')).join('')}</div><h3>${esc(a.name)} · ${cls(a).name}</h3><p>${c.current?esc(R.item(c.current.def).name):'Leerer Slot'} (${c.current?P.config.rarityNames[R.item(c.current.def).rarity]:'—'}) → ${esc(it.name)} (${P.config.rarityNames[it.rarity]})</p>${deltaLine('STÄRKE',c.before,c.after)}${deltaLine('Rolleneignung',c.oldSuitability,c.suitability)}${['Tank','Damage','Healing','Support/Control'].map((name,i)=>deltaLine(name,c.oldValues[i],c.values[i])).join('')}<p>${c.compatible?'Für diese Klasse geeignet.':'Für diese Klasse NICHT geeignet.'} ${R.locked(state,a.id)?'Auf Quest gesperrt.':''} ${a.dead?'Verstorben.':''}</p><div class="row">${btn('Ausstatten','equip-item',{instance,member:a.id},!c.compatible||a.dead||R.locked(state,a.id),'primary')}${btn('Verkaufen · '+c.sell+' Gold','sell-dialog',{instance},false,'quiet')}</div><p class="footer-note">Managementwerte, keine Combatstats. Manuelle Auswahl kann schwächer sein; Auto-Equip nimmt nur echte Verbesserungen vor.</p>`);}
function storageV4(){return title('Die Gildentruhe.','Vergleichen, ausstatten oder verkaufen. Ausgerüstete Items müssen zuerst zurückgegeben werden.',btn('Auto-Equip prüfen','equip',{},false,'primary'))+`<div class="notice">${state.stock.length} freie Ausrüstungsteile · ${state.potions} gemeinsame Heiltränke · unbegrenztes Lager</div><div class="two-col"><section class="stack">${state.stock.length?state.stock.map(e=>{const it=R.item(e.def);return `<article class="card"><div class="row spread"><h3>${esc(it.name)}</h3>${badge(P.config.rarityNames[it.rarity])}</div><p>${it.slot} · Rolleneignung [${it.values.join(' / ')}]</p><p>Verkaufswert: <b>${P.sellValue(e.def)} Gold</b></p><div class="row">${btn('Vergleichen','compare-dialog',{instance:e.instance},false,'primary')}${btn('Verkaufen','sell-dialog',{instance:e.instance},false,'quiet')}</div></article>`;}).join(''):empty('Keine freie Ausrüstung.','Questbeute wird nach Reward-Übernahme automatisch bewertet. Ausgerüstete Items stehen rechts.')}<article class="card"><h3>Heiltränke × ${state.potions}</h3><p>Gemeinsamer Einsatzbestand · ${P.config.potionSellValue} Gold je freiem Trank. Zugewiesene Einsatztränke sind nicht verkaufbar.</p>${btn("1 Heiltrank verkaufen","sell-potion",{quantity:state.potions},state.potions<1,"quiet")}</article></section><section class="stack">${state.members.map(a=>`<article class="card"><h3>${esc(a.name)} · ${cls(a).name}</h3><p>Rang ${esc(a.rank||'F')} · Lvl. ${a.level} · STÄRKE ${P.power(a)}</p>${badge(status(a))}${gear(a)}<footer>${btn('Ausrüstung & Trank zurückgeben','return',{member:a.id},R.locked(state,a.id),'quiet full')}</footer></article>`).join('')}</section></div>`;}
function equipmentFeedback(before,after){const changes=[];for(const a of after.members){const old=before.members.find(b=>b.id===a.id);if(!old)continue;for(const slot of R.slots){const e=a.gear[slot],prev=old.gear[slot];if(e&&e.instance!==prev?.instance){const it=R.item(e.def),oldItem=prev?R.item(prev.def):null;changes.push(`${a.name}: ${oldItem?.name||'Leerer Slot'} → ${it.name}; Stärke ${P.power(a,old.gear)} → ${P.power(a)} (${signed(P.power(a)-P.power(a,old.gear))}); Rolleneignung ${P.suitability(a,oldItem)} → ${P.suitability(a,it)}, ${oldItem?P.config.rarityNames[oldItem.rarity]:'—'} → ${P.config.rarityNames[it.rarity]}`);}}}return changes.join(' · ');}

function hall(){return (F?completionNotices():'')+`<section class="living-hall" aria-label="Deine Gildenhalle"><div class="hall-stage"><img class="painted-environment" src="assets/hall-painted.webp" alt="Räumliche Fantasy-Gildenhalle mit warmem Kamin, Kartentisch, Questbrett und blauem Portal"><img class="hall-occluder occlude-table" src="assets/hall-painted.webp" alt="" aria-hidden="true"><img class="hall-occluder occlude-chest" src="assets/hall-painted.webp" alt="" aria-hidden="true"><img class="hall-occluder occlude-desk" src="assets/hall-painted.webp" alt="" aria-hidden="true"><div class="ambient-fire"><i></i><i></i><i></i></div><div class="ambient-warmth"></div><div class="ambient-portal"><i></i><i></i></div><div class="ambient-candle c1"></div><div class="ambient-candle c2"></div><div class="ambient-candle c3"></div><div class="banner-breath banner-left"></div><div class="banner-breath banner-right"></div><div id="hall-residents" class="hall-residents"></div><div class="guild-master" role="img" aria-label="Du, der Gildenmeister, schreibst am Schreibtisch"><span class="master-piece master-body"></span><span class="master-piece master-head"></span><span class="master-piece master-arm"></span></div><div class="object-hotspots">${btn('<span>Rekrutierung</span>','nav',{page:'recruit'},false,'object-hotspot hotspot-recruit')}${btn('<span>Questbrett</span>','nav',{page:'quests'},false,'object-hotspot hotspot-board')}${btn('<span>Gruppentisch</span>','nav',{page:'party'},false,'object-hotspot hotspot-table')}${btn('<span>Gildentruhe</span>','nav',{page:'storage'},false,'object-hotspot hotspot-chest')}${btn('<span>'+ (D?'Magisches Portal':'Übungsportal') +'</span>','nav',{page:D?'portal':'combat'},false,'object-hotspot hotspot-portal')}${btn('<span>Gildenregister</span>','nav',{page:'roster'},false,'object-hotspot hotspot-register')}</div><div class="hall-title"><span>DIE GILDE</span><small>Ein Zuhause für deine Gefährten</small></div><div class="hall-tip">${state.recruited?'Tippe ein Mitglied oder eine Einrichtung an.':'Deine Halle wartet auf ihre ersten Gefährten.'}</div><span class="hall-save-note">Browser-Playtest · Lokaler Save mit Backup</span></div></section>${D?expeditionSummary():''}`;}
function memberCard(a,extra=''){return`<article class="card candidate-card class-${a.cls.split('.')[1]} ${selection.has(a.id)?'selected':''}" style="--class:${cls(a).color}"><div class="candidate-art">${portrait(a)}<span class="rank-seal">Rang ${esc(a.rank||'F')} · Lvl. ${a.level}</span></div><div class="candidate-info"><span class="eyebrow">${cls(a).name}</span><h3>${esc(a.name)}</h3>${badge(cls(a).role)}${P?badge("STÄRKE "+P.power(a)):""}<p class="candidate-status">Bereit für deine Gilde</p>${extra}</div></article>`;}
function recruit(){const normal=state.recruited,pool=normal?state.normalPool:state.candidates,busy=performance.now()<recruitBusyUntil;return title('Neue Gefährten. Neue Geschichten.',normal?'Rang F · '+(N?'Level '+N.config.ranges[state.poolGuildLevel-1].join('–')+' im aktuellen Pool':'Lvl. 1-Gefährten')+' · '+R.recruitmentConfig.candidateCost+' Gold ab Level 1 · '+state.members.length+'/'+(P?P.limits(state).members:R.recruitmentConfig.guildCapacity)+' Gildenplätze':'Fünf Reisende suchen eine Gilde. Wähle genau drei – kostenlos.')+(P&&state.members.length>=P.limits(state).members?`<div class="notice bad">GILDE VOLL · ${state.members.length}/${P.limits(state).members} Mitglieder. ${P.next(state)?"Nächste Kapazität: Gilden-Lvl. "+P.next(state).level+" ("+P.next(state).members+")":"Maximale Playtest-Kapazität erreicht."}</div>`:"")+`<div class="recruit-banner"><span>${normal?'Die Tür deiner Gilde steht neuen Abenteurern offen.':'STARTERREKRUTIERUNG · 3 AUS 5 KOSTENLOS'}</span>${normal?btn('Neue Kandidaten suchen · '+R.recruitmentConfig.refreshCost+' Gold','refreshPool',{pool:state.poolSeq},busy,'quiet'):badge(selection.size+' / 3 gewählt')}</div><div class="grid candidate-grid">${pool.map(a=>memberCard(a,normal?`<div class="candidate-cost"><i class="coin">G</i> ${recruitCost(a)} Gold</div>${btn('In die Gilde aufnehmen','hire',{candidate:a.id,pool:state.poolSeq},busy,'primary full')}`:btn(selection.has(a.id)?'✓ Ausgewählt':'Diesen Gefährten wählen','candidate',{id:a.id},!selection.has(a.id)&&selection.size>=3,selection.has(a.id)?'primary full':'full'))).join('')}</div>${!pool.length?empty('Alle Gefährten sind angekommen.','Suche für '+R.recruitmentConfig.refreshCost+' Gold nach fünf neuen Kandidaten.'):''}${!normal?`<div class="selection-bar row spread"><span>${selection.size} / 3 Gefährten ausgewählt</span>${btn('Unsere Geschichte beginnt','recruit',{},selection.size!==3,'primary')}</div>`:''}<p class="footer-note">${normal?'Der erste normale Pool ist kostenlos. Höhere Level sind seltener und teurer. Ein vorhandener Pool bleibt bis zur nächsten Suche erhalten.':'Krieger schützen. Priester helfen. Schurken und Magier teilen aus.'}</p>`;}
function gear(a){return`<div class="equipment-slots">${R.slots.map((s,i)=>`<div class="equipment-slot ${a.gear[s]?'filled rarity-common':''}"><span class="slot-icon">${['⚔','♜','⌁'][i]}</span><div><small>${['Waffe','Oberkörper','Beine'][i]}</small><b>${a.gear[s]?esc(R.item(a.gear[s].def).name):'Nicht ausgerüstet'}</b>${a.gear[s]?'<em>'+(P?P.config.rarityNames[R.item(a.gear[s].def).rarity]:'Common')+'</em>':''}</div></div>`).join('')}<div class="potion-slot"><span>♧ Heiltrank</span><b>${a.potion} / 1</b></div></div>`;}
function roster(){return title('Deine Gilde. Deine Gefährten.','Jeder Name erzählt eine Geschichte. Fortschritt und Ausrüstung bleiben bei deiner Gilde.')+(state.members.length?`<div class="grid roster-grid">${state.members.map(a=>{const next=R.thresholds[Math.min(a.level,9)],start=R.thresholds[a.level-1],points=(a.level-1)*3,percent=a.level===10?100:(a.xp-start)/(next-start)*100;return`<article data-roster-member="${esc(a.id)}" class="card roster-card ${a.dead?'is-dead':a.recovery>clock?'is-injured':''}"><div class="roster-top">${portrait(a)}<div><span class="eyebrow">${cls(a).name}</span><h3>${esc(a.name)}</h3><span class="rank-seal">Rang ${esc(a.rank||'F')} · Lvl. ${a.level}</span><p class="${a.dead?'bad':R.available(a,clock)?'good':''}">${status(a)}</p>${P?badge("STÄRKE "+P.power(a)):""}${badge(pname(state.parties.find(p=>p.members.includes(a.id))?.id))}</div></div><div class="row spread"><small>${levelProgress(a)}</small><small>${points} Skillpunkte</small></div><div class="progress xp"><i style="width:${percent}%"></i></div>${gear(a)}<details><summary>Talente deiner Klasse</summary>${GuildSkills[a.cls].map((skill,i)=>`<div class="list-row"><span>${skill.name}</span><b>${Math.max(0,Math.floor((points+8-i)/9))}/3</b></div>`).join('')}</details>${a.dead?`<footer>${btn('Aus Gildenregister entfernen …','remove-dead-dialog',{member:a.id},false,'quiet danger full')}</footer>`:''}</article>`;}).join('')}</div>`:empty('Die Halle wartet auf ihre Gefährten.','Rekrutiere deine ersten drei Mitglieder.','recruit'));}
function empty(h,t,dest){return`<section class="empty"><h2>${h}</h2><p>${t}</p>${dest?btn('Weiter','nav',{page:dest},false,'primary'):''}</section>`;}
function parties(){if(!current()&&state.parties.length)party=state.parties[0].id;const p=current(),free=state.members.filter(a=>!a.dead&&!state.parties.some(p=>p.members.includes(a.id)));return title('Gemeinsam aufbrechen.','1–6 Mitglieder. Ein Mitglied gehört höchstens einer Gruppe an.')+picker()+(P?groupSlots():'')+`<div class="two-col"><section class="card"><h2>${p?esc(p.name):'Keine Gruppe ausgewählt'}</h2>${p?`${P?partyFacts(p):''}<p class="${R.partyLocked(state,p.id)?'bad':'good'}">${R.partyLocked(state,p.id)?'🔒 Bis zur Quest-Auswertung gesperrt':'Bereit zur Verwaltung'}</p>${p.members.map(id=>{const a=member(id);return`<div class="list-row"><div><b>${esc(a.name)}</b> · ${cls(a).name}<br><small>${memberFacts(a)} ${p.leader===id?'· ⚑ Leiter':''}</small></div><div class="row">${btn('Leiter','leader',{member:id},R.partyLocked(state,p.id)||a.dead,'quiet')}${btn('Entfernen','remove',{member:id},R.partyLocked(state,p.id)||p.members.length===1,'quiet')}${state.parties.length>1?btn('Verschieben','transfer-dialog',{member:id},R.partyLocked(state,p.id),'quiet'):''}</div></div>`;}).join('')}<div class="row" style="margin-top:16px">${btn('Leiter leeren','clearLeader',{},R.partyLocked(state,p.id),'quiet')}${btn('Auflösen','dissolve-dialog',{},R.partyLocked(state,p.id),'quiet danger')}${btn('Quest wählen','nav',{page:'quests'},false,'primary')}</div>`:'<p class="muted">Wähle rechts freie Mitglieder und erstelle deine erste Gruppe.</p>'}</section><section class="card"><h2>Freie Mitglieder</h2>${free.length?free.map(a=>`<div class="list-row"><label class="check"><input type="checkbox" data-draft="${a.id}" ${draft.has(a.id)?'checked':''}><span>${esc(a.name)} · ${cls(a).name}<br><small>${memberFacts(a)}</small></span></label>${p?btn('+ zur Gruppe','add',{member:a.id},R.partyLocked(state,p.id)||p.members.length>=6,'quiet'):''}</div>`).join(''):'<p class="muted">Alle lebenden Mitglieder sind bereits zugeordnet.</p>'}<footer>${btn(`Neue Gruppe (${draft.size})`,'createParty',{},draft.size<1||draft.size>6||(P&&state.parties.length>=P.limits(state).groups),'primary full')}</footer></section></div>`;}
const typeNames=['Sammeln','Lieferung','Monsterjagd','Rettung'],typeIcons=['❧','◇','⚔','✚'];
function quests(){if(P)return questsV4();return title('Aufträge am Brett.','F-Rang · normale Gefahr · 60 Sekunden · Empfehlung: 2 Mitglieder')+picker()+`<div class="row spread" style="margin-bottom:15px"><span class="muted">Auswertungsbereite Gruppen belegen weiterhin ihren Questplatz.</span>${btn(showPaid?'Abgeholte ausblenden':'Abgeholte anzeigen','show-paid',{},false,'quiet')}</div><div class="grid">${state.quests.filter(q=>showPaid||!q.paid).map(q=>`<article class="card quest-card ${recentQuest===q.id?'quest-departure':''}"><div class="row spread"><span class="quest-type">${typeIcons[q.type]}</span>${badge(q.status==='Available'?'Verfügbar':q.status==='Active'?'Unterwegs':q.status==='CompletedPendingResolution'?'Rückkehr':'Ausgewertet')}</div><h3 style="margin-top:12px">${q.name}</h3><p class="muted">${typeNames[q.type]} · ${q.distance}</p>${q.status==='Available'?`<small>40 Gold · 60 Gruppen-XP bei Erfolg<br>Beutechance pro Item: 35 %</small><footer>${btn('Mit Gruppe starten','start',{quest:q.id},!current(),'primary full')}</footer>`:q.status==='Active'&&hallModel?.snapshot().some(a=>a.departing&&q.participants.includes(a.id))?'<p class="good">Die Gruppe sammelt sich und bricht auf …</p>':q.status==='Active'?`<div class="progress"><i data-progress="${q.id}" style="width:${Math.min(100,(clock-q.start)/q.duration*100)}%"></i></div><p data-countdown="${q.id}">${Math.max(0,Math.ceil((q.end-clock)/1000))}s verbleibend</p><small>${pname(q.party)} · gesperrt</small>`:q.status==='CompletedPendingResolution'?`<p class="good">${pname(q.party)} wartet auf Auswertung.</p>${(F?btn('Ergebnis ansehen & abschließen','complete-from-hall',{type:'quest',id:q.id},false,'primary full'):btn('Ergebnis auswerten','resolve',{quest:q.id},false,'primary full'))}`:result(q)}</article>`).join('')}</div><div class="selection-bar row spread"><span>Weitere Instanzen der vier vorhandenen Sample-Aufträge.</span>${btn('Vier Aufträge aushängen','offers',{},state.quests.some(q=>q.status==='Available'))}</div>`;}
function result(q){const r=q.result;return`<div class="quest-result ${r.success?'result-success':'result-failure'}"><h3 class="${r.success?'good':'bad'}">${r.wipe?'Wipe':r.success?'Auftrag erfüllt':r.retreat?'Rechtzeitig zurückgezogen':'Ziel nicht erreicht'}</h3><div class="list-row"><b>+${r.gold} Gold</b>${P?badge("+"+(r.guildXP||0)+" Gilden-XP"):""}<span>${r.members.reduce((n,m)=>n+m.xp,0)} XP gesamt</span></div>${r.members.map(m=>`<div class="list-row"><span>${esc(member(m.id).name)}<br><small class="${m.dead?'bad':''}">${m.dead?'Tot':m.injured?`Verletzt · ${m.seconds}s Erholung`:'Unversehrt'}</small></span><b>+${m.xp} XP</b></div>`).join('')}<p style="margin-top:12px">${r.loot.length?r.loot.map(l=>`<span class="loot-reveal">✦ ${l.qty}× ${R.item(l.def).name}</span>`).join(''):'Keine Beute gefunden.'}</p>${q.paid?badge('Rewards übernommen'):btn('XP, Gold & Beute übernehmen','reward',{quest:q.id},false,'primary full')}${q.paid?btn('Buchung erneut prüfen','reward',{quest:q.id},false,'quiet full'):''}</div>`;}
function storage(){if(P)return storageV4();return title('Was der Gilde gehört.','Gemeinsamer Bestand · keine Kapazitätsgrenze · keine Haltbarkeit',btn('Auto-Equip prüfen','equip',{},false,'primary'))+`<div class="notice row spread"><span><b>${state.stock.length}</b> freie Ausrüstungsteile · <b>${state.potions}</b> Heiltränke im Lager</span><small>Tränke werden vor Einsätzen automatisch zugeteilt. Kein Verbrauch im Probekampf.</small></div><div class="two-col"><section class="card"><h2>Gildenlager</h2>${state.stock.length?state.stock.map(e=>`<div class="list-row"><span>${esc(R.item(e.def).name)}<br><small>${e.instance}</small></span>${badge('Common')}</div>`).join(''):'<p class="muted">Keine freie Ausrüstung. Neue Beute wird nach der Reward-Übernahme automatisch bewertet.</p>'}<div class="list-row"><span>Einfacher Heiltrank</span><b>× ${state.potions}</b></div></section><section class="stack">${state.members.map(a=>`<article class="card"><div class="row spread"><h3>${esc(a.name)} · ${cls(a).name}</h3>${badge(status(a))}</div>${gear(a)}<footer>${btn('Ausrüstung & Trank zurückgeben','return',{member:a.id},R.locked(state,a.id),'quiet full')}</footer></article>`).join('')}</section></div>`;}
function combatArena(){if(!combat)return empty('Das Übungsportal ist geöffnet.','Wähle eine freie Gruppe. Hier darfst du kämpfen, ohne deine Gilde zu gefährden.');const s=combat.state;return`<div class="row spread"><h2 id="combat-heading">${s.phase==='TechnicalAbort'?'Technischer Simulationsabbruch':s.result?s.result.wipe?'Gruppe vollständig gefallen':s.result.outcome==='Victory'?'Sieg deiner Gefährten!':'Niederlage':s.phase==='Aftermath'?'Nachsorge':'Die Begegnung beginnt'}</h2><span class="badge" id="combat-clock">${(s.tick/4).toFixed(1)}s</span></div><div class="teams">${['Adventurer','Enemy'].map((side,idx)=>`${idx?'<span class="versus">VS</span>':''}<div class="team">${s.members.filter(a=>a.faction===side).map(a=>`<div data-combatant="${esc(a.id)}" class="fighter ${side==='Enemy'?'enemy':''} life-${a.life}" style="--class:${R.classes[a.def]?.color||'#ba856b'}"><div class="fighter-label"><b>${esc(member(a.id)?.name||a.p.name)}</b><span class="hp-label">${a.hp}/${a.p.hp}</span></div><div class="progress"><i class="hp-value" style="width:${a.hp/a.p.hp*100}%"></i></div>${a.p.mana?`<div class="progress mana"><i class="mana-value" style="width:${a.mana/a.p.mana*100}%"></i></div><small class="mana-label">Mana ${a.mana}/${a.p.mana}</small>`:''}<div class="fighter-stage"><img class="combat-sprite" src="${art(a.def)}" alt="${esc(a.p.name)}"><span class="stun-stars">✦ ✦ ✦</span><div class="combat-fx"></div></div><small class="life-label">${lifeName[a.life]}</small><div class="status-icons">${Object.keys(a.statuses).map(k=>`<span class="status-${k}">${k}</span>`).join('')}</div></div>`).join('')}</div>`).join('')}</div>${s.result?`<p class="footer-note result-banner">${s.result.wipe?'Alle Abenteurer dieser Kampfprobe sind gefallen. ':''}Deine Gilde bleibt unversehrt. ${s.result.participants.filter(x=>x.recovery).length?'Nachsorge: 120s im Folgenvertrag, hier nicht gebucht.':''}</p>`:s.phase==='TechnicalAbort'?'<p class="notice">Die technische Zeitgrenze wurde erreicht. Keine normale Niederlage und keine zusätzlichen Folgen. Starte eine neue Kampfprobe.</p>':''}`;}
const actionLabel=id=>id.split('.').pop().replaceAll('_',' ');
function combatFeedback(events){if(!combat)return;const s=combat.state;const heading=$('#combat-heading');if(heading)heading.textContent=s.phase==='Aftermath'?'Nachsorge':'Die Begegnung läuft';const timer=$('#combat-clock');if(timer)timer.textContent=(s.tick/4).toFixed(1)+'s';
 const cards=[...document.querySelectorAll('[data-combatant]')],card=id=>cards.find(el=>el.dataset.combatant===id);
 for(const a of s.members){const el=card(a.id);if(!el)continue;el.className='fighter '+(a.faction==='Enemy'?'enemy ':'')+'life-'+a.life+(a.statuses.Stun?' stunned':'');el.querySelector('.hp-label').textContent=a.hp+'/'+a.p.hp;el.querySelector('.hp-value').style.width=a.hp/a.p.hp*100+'%';const mana=el.querySelector('.mana-value');if(mana){mana.style.width=a.mana/a.p.mana*100+'%';el.querySelector('.mana-label').textContent='Mana '+a.mana+'/'+a.p.mana;}el.querySelector('.life-label').textContent=lifeName[a.life];el.querySelector('.status-icons').innerHTML=Object.keys(a.statuses).map(k=>`<span class="status-${k}">${k}</span>`).join('');}
 if(reduced())return;
 for(const e of events.slice(-12)){const actor=card(e.actor),target=card(e.target),heal=e.kind.includes('.heal')||e.kind.includes('.stabilize'),death=e.kind.startsWith('death.'),dot=e.kind.startsWith('status.');if(!target||death)continue;
 const sprite=actor?.querySelector('.combat-sprite');if(sprite&&e.actor!==e.target&&!dot&&!heal&&sprite.animate)sprite.animate([{transform:'translateX(0)'},{transform:`translateX(${actor.classList.contains('enemy')?'-':'+'}14px) rotate(-4deg)`},{transform:'translateX(0)'}],{duration:220,easing:'ease-out'});
 const hit=target.querySelector('.combat-sprite');if(hit?.animate)hit.animate(heal?[{filter:'drop-shadow(0 0 0 transparent)'},{filter:'drop-shadow(0 0 14px #a9f18d)'},{filter:'drop-shadow(0 0 0 transparent)'}]:[{transform:'translateX(0)'},{transform:'translateX(-5px)',filter:'brightness(1.7)'},{transform:'translateX(4px)'},{transform:'translateX(0)'}],{duration:e.critical?420:260});
 const fx=target.querySelector('.combat-fx');while(fx.children.length>=3)fx.firstElementChild.remove();const number=document.createElement('span');number.className='combat-number '+(heal?'healing':e.critical?'critical':dot?'dot '+e.kind.split('.')[1]:'damage');number.textContent=(heal?'+':'−')+e.amount+(e.critical?' !':'');fx.appendChild(number);setTimeout(()=>number.remove(),850);}
}
function combatLog(){return combat?combat.log.slice(-12).reverse().map(e=>`<p><span class="muted">${(e.tick/4).toFixed(1)}s</span> ${esc(member(e.actor)?.name||e.actor)} → ${esc(member(e.target)?.name||e.target)}<br><b>${actionLabel(e.kind)} ${e.amount}${e.critical?' · CRIT':''}</b></p>`).join(''):'';}
function combatPage(){if(XP)return practicePage();return title('Ein Blick in den Kampf.','Isolierter Test: keine Rewards, kein Verbrauch, keine dauerhaften Gildenfolgen.')+picker()+`<div class="row" style="margin-bottom:15px"><select id="enemy" aria-label="Gegnerprofil">${Object.entries(R.profiles).filter(([id])=>id.startsWith('enemy')).map(([id,p])=>`<option value="${id}">${p.name}</option>`).join('')}</select><select id="enemy-count" aria-label="Gegneranzahl">${[1,2,3,4,5,6].map(n=>`<option value="${n}">${n} Gegner</option>`).join('')}</select>${btn('Probekampf starten','combat-start',{},!current(),'primary')}${[0,1,2,4].map(n=>btn(n?n+'×':'Pause','speed',{speed:n},!combat||combat.terminal,'quiet')).join('')}</div><div class="combat-layout"><section class="arena" id="arena">${combatArena()}</section><aside class="card"><h3>Was gerade passiert</h3><div class="battle-log" id="battle-log">${combatLog()}</div><p class="footer-note">Tick: 250ms · Seed 7<br>Equipment, Level und Skills combatneutral.</p></aside></div>`;}
function render(){syncHall();resources();if(S)saveIndicator(saveMessage,saveError);$('#content').className='screen screen-'+page;$('#nav').innerHTML=pages.map(([id,icon,label])=>`<button data-action="nav" data-page="${id}" class="${id===page?'active':''}" ${id===page?'aria-current="page"':''}><span class="symbol">${icon}</span>${label}</button>`).join('');const old=$('#content').scrollTop;$('#content').innerHTML=({hall,recruit,roster,party:parties,quests,storage,combat:combatPage,portal:portalPage,'dungeon-prepare':dungeonPrepare,adventure:adventurePage}[page])();$('#content').scrollTop=old;mountHall();mountExpedition();}
function completionNotices(){const rows=[...state.quests.filter(q=>['CompletedPendingResolution','Resolved'].includes(q.status)&&!q.paid).map(q=>({type:'quest',id:q.id,name:q.name,party:q.party})),...D.runs(state).filter(d=>!D.active(d)&&!d.paid).map(d=>({type:'dungeon',id:d.id,name:'Die Goblinmine',party:d.party}))];if(!rows.length)return '';return `<section class="completion-notices" aria-live="polite">${rows.map(r=>`<article class="completion-notice"><div><span class="eyebrow">${r.type==='quest'?'QUEST ABGESCHLOSSEN':'DUNGEON ABGESCHLOSSEN'}</span><h3>${esc(r.name)}</h3><p>${esc(pname(r.party))} ist zurück · Ergebnis bereit.</p></div>${btn('Ergebnis ansehen & abschließen','complete-from-hall',{type:r.type,id:r.id},false,'primary')}</article>`).join('')}</section>`;}
function completionMarkup(type,id){const v=F.entry(state,{type,id}),quest=type==='quest',r=quest?F.preview(state,id):v.reward,ms=quest?r.members:D.partyStates(v),name=quest?v.name:'Die Goblinmine',label=quest?(r.wipe?'Die Gruppe ist gefallen':r.success?'Auftrag erfüllt':r.retreat?'Sicher zurückgezogen':'Ziel nicht erreicht'):dungeonStatus(v);return `<section class="completion-panel" data-completion="${type}" data-paid="${v.paid}"><span class="eyebrow">${v.paid?(saveError?'ABSCHLUSS GEBUCHT · SPEICHERFEHLER':'ABSCHLUSS GESPEICHERT'):'ERGEBNIS BEREIT'}</span><h2>${esc(name)}</h2><h3>${esc(label)}</h3><div class="completion-rewards"><b>+${r.gold} Gold</b><b>+${quest?r.members.reduce((n,m)=>n+m.xp,0):r.xp} ${quest?'Charakter-XP':'Gruppen-XP'}</b><b>+${r.guildXP} Gilden-XP</b></div><div class="completion-members">${ms.map(m=>{const a=member(m.id),dead=quest?m.dead:m.life==='Dead',injured=quest?m.injured:m.recovery>0;return `<div class="list-row"><span>${esc(a?.name||m.id)}</span><strong class="${dead?'bad':injured?'warn':'good'}">${dead?'Gefallen':injured?'Verletzt':quest?'Unversehrt':lifeName[m.life]||m.life}</strong><small>${quest?'+'+m.xp+' XP':m.hp+' HP'}</small></div>`;}).join('')}</div><h3>Beute</h3><p>${r.loot.length?r.loot.map(l=>`${esc(R.item(l.def).name)} × ${l.qty}`).join('<br>'):'Keine Gegenstände gefunden.'}</p>${v.paid?'<p class="good">Bereits übernommen · keine erneute Buchung.</p>'+btn('Zur Gilde','completion-return',{},false,'primary full'):btn(quest?'Quest abschließen':'Dungeon abschließen','completion-finish',{type,id},false,'primary full')}<p class="footer-note">${v.paid?'Gold, XP und Beute sind einmalig gebucht.':'Mit Abschluss werden Ergebnis, Belohnung und Rückkehr zusammen übernommen.'}</p></section>`;}
function openCompletion(type,id,persist=true){const ref={type,id};if(!F.entry(state,ref))return;if(persist){state=R.change(state,'result-open',ref,clock);autosave();}modal(completionMarkup(type,id));}
function finishCompletion(type,id,receipt=false){const before=state,oldLevel=P.guildLevel(state);state=R.change(state,type==='quest'?'finish-quest':'finish-dungeon',{id},clock);if(state!==before){if(receipt)state=R.change(state,'result-open',{type,id},clock);autosave();if(type==='quest')expeditionView.markReturn(id);syncHall();}if(!receipt)$('#dialog').close();go('hall');if(receipt)openCompletion(type,id,false);const raised=P.guildLevel(state)>oldLevel;moment(raised?'level-up':'returning',oldLevel<2&&P.guildLevel(state)>=2?'GILDEN-LEVEL 2 · DUNGEON-PORTAL FREIGESCHALTET':state===before?'Belohnung bereits übernommen.':'Abschluss übernommen · Gruppe ist zurück');if(saveError)toast(saveMessage);}
function readyCompletion(){if(!F||page!=='adventure')return;const ref=watched,v=F.entry(state,ref);if(!v||v.paid||state.adventureUI?.result)return;const ready=ref.type==='quest'?['CompletedPendingResolution','Resolved'].includes(v.status):!D.active(v);if(ready)openCompletion(ref.type,ref.id);}
function resumeAdventure(){if(!F)return;const ui=state.adventureUI||F.empty();if(ui.mode==='watch'&&ui.watch){watched={...ui.watch};page='adventure';}else page='hall';render();if(ui.result)openCompletion(ui.result.type,ui.result.id,false);else readyCompletion();}
function saveView(mode,ref=watched){if(!F)return;state=R.change(state,'view-mode',{mode,...ref},clock);autosave();}

function expeditionSummary(){if(!D)return '';const questRows=state.quests.filter(q=>q.status!=='Available'&&!q.paid),dungeonRows=D.runs(state).filter(d=>!d.paid);if(!questRows.length&&!dungeonRows.length)return `<p class="footer-note">In der Halle erscheinen deine Gruppenleiter. Wähle am Gruppentisch einen Leiter pro Gruppe. ${btn('Magisches Portal','nav',{page:'portal'},false,'quiet')}</p>`;return `<section aria-label="Aktive Expeditionen"><h2>Aktive Expeditionen</h2><div class="expedition-status-grid">${questRows.map(q=>`<article class="expedition-summary"><h3>${esc(q.name)}</h3><p>${esc(pname(q.party))} · ${typeNames[q.type]} · ${q.distance} · ${P.tier(q).name}<br>${q.status==='Active'?XP.journey(q,clock).label:q.status==='CompletedPendingResolution'?(F?'Ergebnis bereit':'Auswertung bereit'):'Zurückgekehrt · Ergebnis bereit'}</p>${btn('Abenteuer ansehen','expedition-open',{type:'quest',id:q.id},false,'quiet')}</article>`).join('')}${dungeonRows.map(d=>`<article class="expedition-summary"><h3>Die Goblinmine</h3><p>${esc(pname(d.party))} · Raum ${d.room+1} / 4<br>${dungeonStatus(d)}</p>${btn(d.status==='Decision'?'Entscheidung öffnen':D.active(d)?'Expedition ansehen':'Ergebnis ansehen','expedition-open',{type:'dungeon',id:d.id},false,'quiet')}</article>`).join('')}</div></section>`;}
function dungeonStatus(d){return d.status==='Combat'?(d.current.speed===0?'Kampf pausiert':d.room===3?'Bosskampf':'Kampf läuft'):({Decision:'Dungeon wartet auf Entscheidung',Completed:'Dungeon abgeschlossen · Boss besiegt',Retreated:'Rückzug · Gruppe zurückgekehrt',Defeat:'Niederlage · Überlebende zurückgekehrt',Wipe:'Wipe · Gruppe gefallen',TechnicalAbort:'Technischer Abbruch · Kein Erfolgsbonus'}[d.status]||d.status);}
function portalPage(){return title('Das magische Portal.','Training oder Expedition – du entscheidest, ob du die Gruppe begleitest.')+`<section class="portal-panel"><div class="portal-door"><span class="portal-emblem">◈</span><div><span class="eyebrow">RANG F · DIE GOBLINMINE</span><h2>Unter dem blauen Erz.</h2><p>Vier Begegnungen führen bis zu Grubenkönig Grak. Zwischen den Räumen entscheidest du, ob die Gruppe weitergeht.</p></div></div><div class="expedition-controls">${btn('Trainingskampf','nav',{page:'combat'},false,'quiet')}${btn(P.guildLevel(state)<2?'🔒 Dungeon · Gilden-Lvl. 2 erforderlich':'Dungeon vorbereiten','nav',{page:'dungeon-prepare'},P.guildLevel(state)<2,'primary')}</div><p class="footer-note">Das Training bleibt ohne Gildenfolgen. In der Mine sind Verletzungen und dauerhafter Tod möglich.</p></section>`+expeditionSummary();}
function dungeonPrepare(){return title('Die Goblinmine.','Wähle eine freie Gruppe für vier aufeinanderfolgende Begegnungen.')+picker()+`<div class="portal-panel"><div class="row spread"><h2>Die Goblinmine</h2>${badge('Rang F · 4 Räume')}</div><p>Empfohlene Management-Stärke: <b>${D.config.recommended}</b> · empfohlen: vier gesunde Mitglieder mit Tank, Heilung und Schaden.</p><p class="footer-note">Im vorhandenen Kampfmodell zählen Klassen und Gruppengröße. Level und Ausrüstung erhöhen hier noch keinen Kampfschaden. HP werden in den nächsten Raum übernommen; Mana regeneriert beim Raumbeginn. Kampfunfähige bleiben bis zur Rückkehr außer Gefecht.</p>${current()?`<h3>${esc(current().name)} · Leiter: ${esc(member(current().leader)?.name||'nicht gewählt')}</h3>${partyFacts(current())}<div class="stack">${current().members.map(id=>`<div class="list-row"><b>${esc(member(id).name)}</b><span>${memberFacts(member(id))}</span></div>`).join('')}</div>`:''}<div class="dungeon-room-strip">${D.config.rooms.map((r,i)=>`<span>${i+1}. ${r.name}</span>`).join('')}</div><p>Gesicherte Raumbeute bleibt bei Rückzug erhalten. Bossbonus nur beim Sieg. Belohnung nach Ende einmalig übernehmen.</p><h3>Wie möchtest du die Expedition verfolgen?</h3><div class="expedition-choice">${btn('Abenteuer begleiten','dungeon-launch',{mode:'watch'},!current()||P.guildLevel(state)<2,'primary')}${btn('Manager-Modus','dungeon-launch',{mode:'manager'},!current()||P.guildLevel(state)<2,'quiet')}</div></div>`;}
function stageMarkup(environment='mine',boss=false){return `<div class="adventure-stage" data-environment="${environment}"><div class="adventure-backdrop"></div><div class="adventure-ground"></div>${F?'<div class="scene-light"></div><div class="scene-mist"></div><div class="scene-motes" aria-hidden="true">'+Array.from({length:8},(_,i)=>'<i style="--mote:'+i+'"></i>').join('')+'</div><div class="scene-foreground"></div>':''}<div class="adventure-vignette"></div><div id="adventure-actors" class="adventure-actors"></div><div class="journey-objective"></div><div class="adventure-scene-title"><div><h2 data-scene-phase>Deine Expedition</h2><small data-scene-detail>Die Gruppe ist unterwegs.</small></div>${boss?'<div class="boss-health"><b data-boss-hp>Grubenkönig Grak</b><div class="progress"><i data-boss-bar></i></div></div>':''}</div></div>`;}
function adventurePage(){const dungeon=watched.type==='dungeon',d=dungeon?D.runs(state).find(d=>d.id===watched.id):null,q=!dungeon?state.quests.find(q=>q.id===watched.id):null;if(!d&&!q)return empty('Keine Expedition gewählt.','Öffne einen laufenden Einsatz aus der Halle.');
 const titleText=d?'Die Goblinmine':q.name,statusText=d?dungeonStatus(d):XP.journey(q,clock,expeditionView.returnTimes.get(q.id)??null).label;
 const speeds=d?[0,1,2,4].map(n=>btn(n?n+'×':'Pause','dungeon-speed',{id:d.id,speed:n},d.status!=='Combat',d.current?.speed===n?'active':'quiet')).join(''):[0,1,2,4].map(n=>btn(n?n+'×':'Pause','journey-speed',{speed:n},false,journeySpeed===n?'active':'quiet')).join('');
 return `<div class="row spread"><div><span class="eyebrow">${d?'DUNGEONEXPEDITION':'BEGLEITETE QUEST'}</span><h1>${esc(titleText)}</h1></div>${btn('Zur Gilde','expedition-leave',{},false,'quiet')}</div><div class="expedition-controls">${speeds}<span class="footer-note">${d?'Explizite Pause bleibt auch in der Halle bestehen.':'Nur Reiseanimation · Questzeit läuft unverändert weiter.'}</span></div><div class="adventure-layout">${stageMarkup(d?'mine':'road',d?.room===3)}<aside class="expedition-side"><section class="card"><h3>${esc(pname(d?.party||q?.party))}</h3><p>${statusText}</p>${d?dungeonDetails(d):questAdventureDetails(q)}</section></aside></div>`;
}
function questAdventureDetails(q){if(F&&['CompletedPendingResolution','Resolved'].includes(q.status))return `${questFacts(q)}${btn(q.paid?'Ergebnis ansehen':'Quest abschließen','completion-open',{type:'quest',id:q.id},false,'primary full')}`;return `${questFacts(q)}<p>Die Reise stellt deine Quest dar. Erfolg und Lebensfolgen stehen erst nach der Auswertung fest.</p>${q.status==='CompletedPendingResolution'?btn('Ergebnis auswerten','journey-resolve',{quest:q.id},false,'primary full'):q.status==='Resolved'?result(q):'<p data-countdown="'+q.id+'">'+Math.max(0,Math.ceil((q.end-clock)/1000))+'s verbleibend</p>'}`;}
function dungeonDetails(d){return `<div class="dungeon-room-strip">${D.config.rooms.map((r,i)=>`<span class="${i<d.room?'done':i===d.room?'current':''}">${i<d.room?'✓ ':''}${i+1}</span>`).join('')}</div><p>${D.partyStates(d).map(m=>`${esc(member(m.id)?.name||m.id)} · ${m.hp} HP · ${lifeName[m.life]||m.life}`).join('<br>')}</p><p>Gesichert: ${d.secured.gold} Gold · ${d.secured.xp} Gruppen-XP · ${d.secured.guildXP} Gilden-XP<br>${d.secured.loot.length} Beuteposten</p>${d.status==='Decision'?`<h3>Raum geschafft</h3><p>Die Gruppe wartet auf deine Entscheidung. Nächster Abschnitt: ${D.config.rooms[d.room+1].name}</p><div class="stack">${btn('Weiter','dungeon-next',{id:d.id,room:d.room},false,'primary')}${btn('Dungeon verlassen','dungeon-retreat',{id:d.id,room:d.room},false,'quiet')}</div>`:D.active(d)?'<p>Du beobachtest. Die Abenteurer kämpfen selbst.</p>':`<h3>${d.status==='Completed'?'Boss besiegt':dungeonStatus(d)}</h3><p>${d.reward.loot.map(l=>esc(R.item(l.def).name)+' × '+l.qty).join('<br>')||'Keine Gegenstände'}</p>${d.paid?badge('Belohnung übernommen'):(F?btn('Dungeon abschließen','completion-open',{type:'dungeon',id:d.id},false,'primary full'):btn('Belohnung übernehmen','dungeon-claim',{id:d.id},false,'primary full'))}`}`;}
function practicePage(){return title('Der Trainingsplatz.','Isolierter Combat-Test: keine Rewards und keine dauerhaften Gildenfolgen.')+picker()+`<div class="expedition-controls"><select id="enemy" aria-label="Gegnerprofil">${Object.entries(R.profiles).filter(([id])=>id.startsWith('enemy')).map(([id,p])=>`<option value="${id}">${p.name}</option>`).join('')}</select><select id="enemy-count" aria-label="Gegneranzahl">${[1,2,3,4,5,6].map(n=>`<option value="${n}">${n} Gegner</option>`).join('')}</select>${btn('Probekampf starten','combat-start',{},!current(),'primary')}${[0,1,2,4].map(n=>btn(n?n+'×':'Pause','speed',{speed:n},!combat||combat.terminal,'quiet')).join('')}</div>${combat?`<div class="adventure-layout">${stageMarkup('camp')}<aside class="card"><h3>Kampfprotokoll</h3><div id="battle-log" class="adventure-log">${combatLog()}</div><p class="footer-note">Training: Die Gilde bleibt unverändert.</p></aside></div>`:empty('Die Arena ist bereit.','Wähle eine freie Gruppe und starte den Probekampf.')}`;}
function mountExpedition(){if(!XP)return;let layer=null,key='',core=null;if(page==='adventure'){layer=$('#adventure-actors');key=watched.type+':'+watched.id;if(watched.type==='dungeon'){const d=D.runs(state).find(d=>d.id===watched.id);core=(d?.current||d?.encounters.at(-1)?.combat)?.state;}}else if(page==='combat'&&combat){layer=$('#adventure-actors');key='practice';core=combat.state;}expeditionView.mount(layer,key,core);updateExpedition(0);}
function updateExpedition(dt){if(!XP)return;if(page==='adventure'){const context=watched.type==='dungeon'?{type:'dungeon',run:D.runs(state).find(d=>d.id===watched.id),state}:{type:'quest',quest:state.quests.find(q=>q.id===watched.id),state,clock,visualSpeed:journeySpeed};if(context.run||context.quest)expeditionView.update(context,dt,reduced());}else if(page==='combat'&&combat)expeditionView.update({type:'practice',combat,state},dt,reduced());}
function watchExpedition(type,id){watched={type,id};pendingWatch=null;if(F)saveView('watch');go('adventure');readyCompletion();}
function afterDeparture(type,id,mode){go('hall');if(F)saveView(mode==='watch'?'watch':'manager',{type,id});if(mode==='watch'){if(hallModel?.snapshot().some(a=>a.departing))pendingWatch={type,id};else watchExpedition(type,id);}}
function dungeonAction(op,args){const before=state;state=R.change(state,op,args,clock);if(state!==before){autosave();if(op==='dungeon-next'&&D.runs(state).find(d=>d.id===args.id)?.room===3)moment('departure','BOSS ERREICHT · Grubenkönig Grak');if(op==='dungeon-start')moment('departure','Die Gruppe betritt das Dungeon-Portal.');if(op==='dungeon-claim'){state=R.change(state,'equip',{},clock);autosave();moment('reward','Dungeonbelohnung übernommen · +'+(state.gold-before.gold)+' Gold');}if(!before.expeditions?.portalAnnounced&&state.expeditions?.portalAnnounced)moment('level-up','DUNGEON-PORTAL FREIGESCHALTET · Gilden-Lvl. 2');syncHall();}else toast('Bereits gebucht – keine doppelte Belohnung.');}
const journeyNotices=new Map();
function journeyNotifications(){if(!XP)return;for(const q of state.quests){if(q.status!=='Active')continue;const phase=XP.journey(q,clock).phase,old=journeyNotices.get(q.id);journeyNotices.set(q.id,phase);if(old&&old!==phase&&phase==='objective'){toast(q.name+' · Zielgebiet erreicht. Ausgang noch offen.');if(page==='hall')render();}}}
function tickDungeons(){if(!D)return;const before=state,statuses=D.runs(state).map(d=>d.status).join('|');state=D.advance(state,clock,(id,core,events,speed)=>expeditionView.ingest(id,core,events,speed));if(state!==before){const changed=statuses!==D.runs(state).map(d=>d.status).join('|');if(changed||clock-lastDungeonSave>=5000){autosave();lastDungeonSave=clock;}if(changed){syncHall();render();const d=D.runs(state).find((d,i)=>d.status!==D.runs(before)[i]?.status);if(d){moment('returning',dungeonStatus(d));toast(dungeonStatus(d));if(F)readyCompletion();}}}}

function modal(html){$('#dialog-content').innerHTML=html;if(!$('#dialog').open)$('#dialog').showModal();}
function apply(op,args={}){args.party??=party;const before=state;state=R.change(state,op,args,clock);if(state!==before)autosave();if(op==='reward'&&state!==before){try{state=R.change(state,'equip',{},clock);autosave();}catch(e){toast('Belohnung gebucht. Auto-Equip offen: '+e.message);return;}const raised=state.members.filter(a=>a.level>(before.members.find(b=>b.id===a.id)?.level||a.level));moment(raised.length?'level-up':'reward',raised.length?raised.map(a=>a.name+' erreicht Rang F · Lvl. '+a.level+' · +'+((a.level-before.members.find(b=>b.id===a.id).level)*3)+' Skillpunkte').join(' · '):(()=>{const r=state.quests.find(q=>q.id===args.quest).result;return '+'+r.gold+' Gold · +'+r.members.reduce((n,m)=>n+m.xp,0)+' Charakter-XP · '+(P?'+'+(r.guildXP||0)+' Gilden-XP · ':'')+r.loot.length+' Beutefunde';})());}
 if(op==='start'){recentQuest=args.quest;moment('departure','Deine Gefährten brechen auf!');setTimeout(()=>recentQuest='',650);}
 if(op==='hire'){lockRecruit();moment('arrival',state.members.at(-1).name+' tritt deiner Gilde bei · −'+recruitCost(state.members.at(-1))+' Gold');}
 if(op==='refreshPool'){lockRecruit();moment('arrival','Neue Gefährten sind angekommen · −'+R.recruitmentConfig.refreshCost+' Gold');}
 if(D&&!before.expeditions?.portalAnnounced&&state.expeditions?.portalAnnounced)moment('level-up','DUNGEON-PORTAL FREIGESCHALTET · Gilden-Lvl. 2');
 syncHall();
 toast(op==='reward'&&state===before?'Bereits gebucht – keine doppelte Belohnung.':({recruit:'Drei Gefährten sind angekommen. Der erste normale Pool ist kostenlos bereit.',createParty:'Eine neue Gruppe ist bereit.',start:'Gruppe aufgebrochen.',resolve:'Die Gruppe ist zurück. Belohnung jetzt übernehmen.',reward:'XP, Gold und Beute übernommen.',equip:'Ausrüstung neu bewertet.',hire:'Neues Mitglied aufgenommen.',refreshPool:'Fünf neue Kandidaten warten.',removeDead:'Ein Platz im Gildenregister ist frei.'}[op]||'Erledigt.'));if(P){const feedback=equipmentFeedback(before,state);if(feedback)toast((op==='equipItem'?'Ausgestattet. ':'Auto-Equip: bessere Rolleneignung bzw. Rarity bei Gleichstand. ')+feedback);if(op==='sellPotion'&&state!==before)toast('Heiltrank verkauft · +'+P.config.potionSellValue+' Gold');if(op==='sell'&&state!==before){const sold=before.stock.find(e=>e.instance===args.instance);toast(R.item(sold.def).name+' verkauft · +'+(state.gold-before.gold)+' Gold');}if(op==='reward'&&state!==before){const oldLevel=P.guildLevel(before),newLevel=P.guildLevel(state);if(newLevel>oldLevel){const old=P.limits(before),now=P.limits(state);moment('level-up','GILDEN-LEVEL AUFGESTIEGEN! '+oldLevel+' → '+newLevel+' · '+unlocks({extraGroups:now.groups-old.groups,extraMembers:now.members-old.members,extraMissions:now.missions-old.missions})+(D&&oldLevel<2&&newLevel>=2?' · DUNGEON-PORTAL FREIGESCHALTET':''));}}}}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const d=el.dataset;try{switch(d.action){case'nav':pendingWatch=null;if(F&&state.adventureUI?.mode==='watch')saveView('manager');go(d.page);return;case'pick':party=d.id;break;case'candidate':selection.has(d.id)?selection.delete(d.id):selection.add(d.id);break;case'recruit':apply('recruit',{ids:[...selection]});go('hall');return;case'hire':if(performance.now()<recruitBusyUntil)return;apply('hire',{candidate:d.candidate,pool:Number(d.pool)});go('hall');return;case'refreshPool':if(performance.now()<recruitBusyUntil)return;apply('refreshPool',{pool:Number(d.pool)});break;case'remove-dead-dialog':modal(`<h2>${esc(member(d.member).name)} endgültig aus dem Gildenregister entfernen?</h2><p>Nur dieser verstorbene Gefährte wird dauerhaft aus der aktuellen Gilde entfernt. Der Platz wird frei. Diese Aktion kann nicht rückgängig gemacht werden.</p>${btn('Endgültig entfernen','removeDead',{member:d.member},false,'danger')}`);return;case'removeDead':apply('removeDead',{member:d.member,confirmed:true});$('#dialog').close();break;case'createParty':apply('createParty',{ids:[...draft]});draft.clear();party=state.parties.at(-1).id;break;case'show-paid':showPaid=!showPaid;break;
 case'completion-open':openCompletion(d.type,d.id);return;
 case'completion-finish':finishCompletion(d.type,d.id);return;
 case'complete-from-hall':finishCompletion(d.type,d.id,true);return;
 case'completion-return':state=R.change(state,'result-close',{},clock);autosave();$('#dialog').close();go('hall');return;
 case'expedition-open':watchExpedition(d.type,d.id);return;
 case'expedition-leave':pendingWatch=null;if(F)saveView('manager');go('hall');return;
 case'journey-speed':journeySpeed=Number(d.speed);render();return;
 case'quest-launch':{const q=state.quests.find(q=>q.id===d.quest);if(!q)throw Error('Quest fehlt.');apply('start',{quest:q.id,party:d.party,confirmed:d.confirmed==='true'});$('#dialog').close();afterDeparture('quest',q.id,d.mode);return;}
 case'journey-resolve':apply('resolve',{quest:d.quest});expeditionView.markReturn(d.quest);render();return;
 case'dungeon-launch':{dungeonAction('dungeon-start',{party});const run=D.runs(state).at(-1);afterDeparture('dungeon',run.id,d.mode);return;}
 case'dungeon-next':case'dungeon-retreat':case'dungeon-claim':case'dungeon-speed':dungeonAction(d.action,{id:d.id,room:Number(d.room),speed:Number(d.speed)});render();if(F)readyCompletion();return;
 case'save-now':autosave();return;
 case'save-export':if(S)exportCurrent();return;
 case'save-import':if(S)$('#save-import').click();return;
 case'guild-info':if(P)modal(guildDetails());return;
 case'compare-dialog':case'compare-target':comparisonDialog(d.instance,d.member);return;
 case'equip-item':apply('equipItem',{instance:d.instance,member:d.member});$('#dialog').close();break;
 case'sell-dialog':{const e=state.stock.find(e=>e.instance===d.instance);if(!e)throw Error('Item nicht mehr im Lager.');const it=R.item(e.def),value=P.sellValue(e.def);if(it.rarity===2||value>=P.config.valuable){modal(`<h2>Wertvolles Item wirklich verkaufen?</h2><p>${esc(it.name)} · ${P.config.rarityNames[it.rarity]} · ${value} Gold</p>${btn('Verkaufen','sell',{instance:d.instance},false,'danger')}<p>Zum Abbrechen: Schließen.</p>`);return;}apply('sell',{instance:d.instance});$('#dialog').close();break;}
 case'sell-potion':apply('sellPotion',{expectedQuantity:Number(d.quantity)});break;
 case'sell':apply('sell',{instance:d.instance,confirmed:true});$('#dialog').close();break;
 case'transfer-dialog':modal(`<h2>Mitglied verschieben</h2><p>${esc(member(d.member).name)} aus ${esc(pname(party))}</p><div class="stack">${state.parties.filter(p=>p.id!==party).map(p=>btn(p.name,'transfer',{member:d.member,to:p.id},R.partyLocked(state,p.id)||p.members.length>=6)).join('')}</div>`);return;
 case'dissolve-dialog':modal(`<h2>Gruppe auflösen?</h2><p>Alle Mitglieder werden frei. Es gehen keine Mitglieder oder Items verloren.</p>${btn('Gruppe auflösen','dissolve',{},false,'danger')}`);return;
 case'transfer':apply('transfer',{member:d.member,to:d.to});$('#dialog').close();break;case'dissolve':apply('dissolve');party='';$('#dialog').close();break;
 case'leader':case'remove':case'add':case'return':apply(d.action,{member:d.member});draft.delete(d.member);break;
 case'clearLeader':case'offers':case'equip':apply(d.action);break;
 case'start':if(P){const v=P.previewStart(state,d.quest,party,clock);if(v.warn&&d.confirmed!=='true'){modal(`<h2>WARNUNG · ${v.label}</h2><p>Empfohlene Stärke: ${v.recommended}<br>Deine Gruppe nach Vorbereitung: ${v.strength}</p><p>Diese Gruppe ist deutlich schwächer als empfohlen. Verletzung und dauerhafter Tod sind möglich.</p>${btn('Trotzdem starten','start',{quest:d.quest,confirmed:'true'},false,'danger')}<p>Zum Abbrechen: Schließen.</p>`);return;}}if(XP){modal(`<h2>Wie möchtest du die Expedition verfolgen?</h2><p>${esc(state.quests.find(q=>q.id===d.quest).name)} · ${esc(pname(party))}</p><div class="expedition-choice">${btn('Abenteuer begleiten','quest-launch',{quest:d.quest,party,confirmed:d.confirmed||'false',mode:'watch'},false,'primary')}${btn('Manager-Modus','quest-launch',{quest:d.quest,party,confirmed:d.confirmed||'false',mode:'manager'},false,'quiet')}</div>`);return;}apply('start',{quest:d.quest,confirmed:d.confirmed==='true'});$('#dialog').close();go('hall');return;case'resolve':apply('resolve',{quest:d.quest});go('hall');return;case'reward':apply('reward',{quest:d.quest});break;
 case'combat-start':{const p=current();if(!p||R.partyLocked(state,p.id)||p.members.some(id=>!R.available(member(id),clock)||R.locked(state,id)))throw Error('Die gesamte Gruppe muss frei und einsatzfähig sein.');const inputs=p.members.map(id=>{const a=member(id);return C.input(a.id,a.cls,a.id,R.slots.map(s=>a.gear[s]));});for(let i=0;i<Number($('#enemy-count').value);i++)inputs.push(C.input('enemy.'+i,$('#enemy').value));combat=new C.Combat(inputs,7);if(XP)expeditionView.timeline.reset(combat.state);toast('Probekampf gestartet – Gildenbestand bleibt unverändert.');break;}
 case'speed':if(combat&&!combat.terminal){combat.speed=Number(d.speed);toast(combat.speed?combat.speed+'×':'Kampf pausiert');}return;
 case'advance':clock+=60000;R.refresh(state,clock);tickDungeons();autosave();toast('Entwicklungsuhr +60s.');break;
 case'reset-confirm':resetArmed=true;modal(`<h2>Neue Gilde beginnen?</h2><p>Der aktuelle Spielstand und beide lokalen Saves (Primary und Backup) werden gelöscht. Vorher bei Bedarf exportieren.</p>${btn('Zurücksetzen','reset',{},false,'danger')}`);return;
 case'reset':if(S){if(!resetArmed)throw Error('Neue Gilde zuerst ausdrücklich bestätigen.');if(!store)throw Error('Lokaler Speicher nicht verfügbar; Löschen nicht möglich.');store.deleteSave(true);resetArmed=false;}if(hallModel){hallModel.actors.clear();hallModel.memberIds.clear();hallModel.questStatus.clear();hallModel.initialized=false;}pendingWatch=null;if(XP){expeditionView.mount(null,'');expeditionView.returnTimes.clear();}state=R.initial();shownGold=null;recruitBusyUntil=0;combat=null;party='';selection.clear();draft.clear();clock=1000;showPaid=false;$('#dialog').close();if(S){resourcesV4.stamp=null;autosave();go('recruit');}else go('hall');toast('Neue Gilde gestartet.');return;
 case'about':modal('<h2>Browser-Playtest</h2><p>Eigenständige JavaScript-Umsetzung. Kein Unity-Build. V4.2A speichert lokal mit Backup; JSON-Export über Werkzeuge.</p><p>Bestehende Questformeln, Rang-F-XP bis Level 10, 3 Skillpunkte/Level, Itemkatalog, Sperren und Combatregeln sind übernommen.</p><p>JavaScript-Zahlen statt C# decimal; Item-/Result-IDs sind browserlokal. Grafik ist eine 2D-Präsentation. Nur das Training bleibt ohne Gildenfolgen; die Goblinmine übernimmt autoritative Lebensfolgen.</p><p>Nach der Starterrunde: Rang F · Lvl. 1-Rekrutierung für 50 Gold, neue Kandidaten für 25 Gold. Verstorbene können nach Abholung offener Belohnungen bestätigt entfernt werden. Höhere Rekrutenlevel abhängig vom Gilden-Level; Preis auf der Karte. Keine Wiederbelebung.</p>');return;
 }render();}catch(err){toast(err.message);}});
document.addEventListener('change',e=>{if(e.target.id==='save-import'){importSelected(e.target.files?.[0]);return;}if(e.target.dataset.draft){const id=e.target.dataset.draft;e.target.checked?draft.add(id):draft.delete(id);render();}});
$('#tools').onclick=()=>modal(`<h2>Playtest-Werkzeuge</h2><p>${S?'Lokaler Save mit Backup. Offline-Zeit läuft weiter. Import ersetzt nach vollständiger Prüfung die aktuelle Gilde.':'Kein Save.'}</p><p class="${saveError?'bad':'muted'}">${esc(saveMessage)}</p><div class="stack">${S?btn('Spiel speichern','save-now')+btn('Spielstand exportieren','save-export')+btn('Spielstand importieren …','save-import'):''}${btn('+60s Quest / Erholung','advance')}${btn('Neue Gilde …','reset-confirm',{},false,'danger')}${btn('Regeln & Unterschiede','about')}</div>`);
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(combat)combat.speed=0;if(S&&!saveError)autosave();}});
if(S)$('#dialog').addEventListener('close',()=>{resetArmed=false;if(F&&state.adventureUI?.result&&!$('#dialog').open){state=R.change(state,'result-close',{},clock);autosave();}});
if(S)window.addEventListener('pagehide',()=>{if(!saveError)autosave();});
setInterval(()=>{const n=performance.now(),dt=n-previous;previous=n;clock+=dt;let changed=state.quests.filter(q=>q.status==='Active'&&clock>=q.end).length;R.refresh(state,clock);syncHall();resources();tickDungeons();journeyNotifications();if(changed){autosave();render();moment('returning',F?'QUEST ABGESCHLOSSEN · Ergebnis bereit':'Ein Questresultat wartet am Questbrett.');toast(F?'QUEST ABGESCHLOSSEN · Ergebnis direkt verfügbar.':'Eine Gruppe wartet auf Auswertung.');if(F){if(page==='hall')moment('returning','QUEST ABGESCHLOSSEN · Gruppe ist zurück');readyCompletion();}}
 for(const el of document.querySelectorAll('[data-countdown]')){const q=state.quests.find(q=>q.id===el.dataset.countdown);el.textContent=Math.max(0,Math.ceil((q.end-clock)/1000))+'s verbleibend';}
 for(const el of document.querySelectorAll('[data-progress]')){const q=state.quests.find(q=>q.id===el.dataset.progress);el.style.width=Math.min(100,(clock-q.start)/q.duration*100)+'%';}
 if(page==='combat'&&combat&&!combat.terminal&&combat.speed){const tick=combat.state.tick;combat.advance(Math.min(dt,2000));if(XP)expeditionView.timeline.ingest(combat.state,combat.log.filter(e=>e.tick>tick),combat.speed);else combatFeedback(combat.log.filter(e=>e.tick>tick));$('#battle-log').innerHTML=combatLog();if(combat.terminal){render();moment(combat.state.phase==='TechnicalAbort'?'technical':combat.state.result?.outcome==='Victory'?'victory':'defeat',combat.state.phase==='TechnicalAbort'?'Technische Zeitgrenze · keine Niederlage':combat.state.result?.wipe?'Die Gruppe ist gefallen':combat.state.result?.outcome==='Victory'?'Sieg deiner Gefährten!':'Deine Gruppe wurde besiegt');}}
},250);
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 const tools=[{name:'read_guild_playtest',description:'Read the current in-memory guild playtest snapshot. No mutation.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>R.clone({page,clock,state,combat:combat?.state||null})},
 {name:'navigate_guild_playtest',description:'Navigate to a guild screen. Leaving combat pauses the practice fight.',inputSchema:{type:'object',properties:{page:{type:'string',enum:pages.map(p=>p[0])}},required:['page'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!pages.some(p=>p[0]===input.page))throw Error('Unknown page');go(input.page);return{page};}}];
 for(const tool of tools)try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch(_){}
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
if(F&&!saveError)resumeAdventure();else render();
if(S&&saveError)modal('<h2>Spielstand konnte nicht geladen werden</h2><p>'+esc(saveMessage)+'</p><p>Vorhandene Daten wurden nicht überschrieben. Über Werkzeuge einen Save importieren oder Neue Gilde ausdrücklich bestätigen.</p>');
else if(S&&saveMessage.includes('Backup'))toast(saveMessage);
if(typeof requestAnimationFrame==='function')requestAnimationFrame(hallFrame);
})();
