/* Browser presentation and in-memory service composition, separate from the Unity project. */
(()=>{'use strict';const R=GuildRules,C=GuildCombat,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=R.initial(),page='hall',selection=new Set(),draft=new Set(),party='',showPaid=false,combat=null,clock=1000,previous=performance.now(),toastTimer,recruitBusyUntil=0,recentQuest='',shownGold=null;
const pages=[['hall','⌂','Halle'],['recruit','✦','Rekrutierung'],['roster','♙','Mitglieder'],['party','⚑','Gruppen'],['quests','▤','Quests'],['storage','▣','Lager'],['combat','⚔','Probekampf']];
const btn=(label,action,data={},disabled=false,kind='')=>`<button class="${kind}" data-action="${action}" ${Object.entries(data).map(([k,v])=>`data-${k}="${esc(v)}"`).join(' ')} ${disabled?'disabled':''}>${label}</button>`;
const member=id=>state.members.find(a=>a.id===id)||state.retiredMembers.find(a=>a.id===id),pname=id=>state.parties.find(p=>p.id===id)?.name||'Keine Gruppe',current=()=>state.parties.find(p=>p.id===party),status=a=>a.dead?'Tot':a.recovery>clock?`Verletzt · ${Math.ceil((a.recovery-clock)/1000)}s`:'Einsatzfähig';
const cls=a=>R.classes[a.cls],title=(n,text='',action='')=>`<div class="page-title"><div><div class="eyebrow">DIE GILDE · ABENTEUER BEGINNEN HIER</div><h1>${n}</h1><p>${text}</p></div>${action}</div>`;
const portrait=a=>`<div class="portrait ${a.dead?'portrait-dead':a.recovery>clock?'portrait-injured':''}" style="--class:${cls(a).color}"><img src="assets/${a.cls.split('.')[1]}.svg" alt="${cls(a).name}" draggable="false">${a.dead?'<span class="portrait-status">Verstorben</span>':a.recovery>clock?'<span class="portrait-status">Verletzt</span>':''}</div>`;
const art=def=>'assets/'+(def.startsWith('enemy.')?'goblin-'+def.split('.').at(-1):def.split('.')[1])+'.svg';
const lifeName={Alive:'Kampfbereit',Incapacitated:'Kampfunfähig',Stabilized:'Stabilisiert',Dead:'Gefallen'};
const reduced=()=>typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches;
function moment(kind,text){const box=$('#moment');if(!box)return;box.className='moment '+kind;box.textContent=text;box.hidden=false;clearTimeout(moment.timer);moment.timer=setTimeout(()=>box.hidden=true,3000);}
function lockRecruit(){recruitBusyUntil=performance.now()+500;setTimeout(()=>{if(page==='recruit')render();},510);}
const badge=t=>`<span class="badge">${esc(t)}</span>`;
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',4200);}
function go(target){if(page==='combat'&&target!=='combat'&&combat)combat.speed=0;page=target;render();$('#content').scrollTop=0;}
function resources(){const gold=state.gold;if(shownGold!==gold){const delta=shownGold===null?0:gold-shownGold;$('#resources').innerHTML=`<span class="gold-resource ${delta?'resource-flash':''}"><i class="coin">G</i><b>${gold}</b><small>Gold</small>${delta?`<em class="resource-change ${delta<0?'spend':''}">${delta>0?'+':''}${delta}</em>`:''}</span><span><b>${state.members.length}/12</b><small>Mitglieder</small></span><span><b>${state.quests.filter(q=>['Active','CompletedPendingResolution'].includes(q.status)).length}/3</b><small>Einsätze</small></span>`;shownGold=gold;}else{const nodes=$('#resources').querySelectorAll?$('#resources').querySelectorAll('span > b'):[];if(nodes[1])nodes[1].textContent=state.members.length+'/12';if(nodes[2])nodes[2].textContent=state.quests.filter(q=>['Active','CompletedPendingResolution'].includes(q.status)).length+'/3';}}
function picker(){if(!state.parties.length)return`<div class="notice">Erst eine Gruppe zusammenstellen. ${btn('Zu den Gruppen','nav',{page:'party'})}</div>`;if(!current())party=state.parties[0].id;return`<div class="pill-row">${state.parties.map(p=>btn(`${esc(p.name)} · ${p.members.length}${R.partyLocked(state,p.id)?' 🔒':''}`,'pick',{id:p.id},false,p.id===party?'active':'quiet')).join('')}</div>`;}
function hall(){const pending=state.quests.filter(q=>q.status==='CompletedPendingResolution').length;const next=!state.recruited?'recruit':!state.parties.length?'party':'quests';return `<section class="guild-hall" aria-label="Deine Gildenhalle"><img class="hall-art" src="assets/guild-hall.svg" alt="Warme steinerne Gildenhalle mit Kamin, Schreibtisch, Questbrett, Rekrutierungstisch, Gildentruhe und magischem Portal"><div class="hall-light hearth"></div><div class="hall-light portal-light"></div><div class="hall-welcome"><span class="eyebrow">WILLKOMMEN ZURÜCK, GILDENMEISTER</span><h1>Hier beginnt<br>eure Geschichte.</h1></div><div class="hall-locations">${btn('<span>✦</span><b>Rekrutierung</b>','nav',{page:'recruit'},false,'location recruitment')}${btn('<span>▤</span><b>Questbrett</b>','nav',{page:'quests'},false,'location board')}${btn('<span>⚑</span><b>Gruppentisch</b>','nav',{page:'party'},false,'location table')}${btn('<span>▣</span><b>Gildentruhe</b>','nav',{page:'storage'},false,'location chest')}${btn('<span>⚔</span><b>Übungsportal</b>','nav',{page:'combat'},false,'location portal')}${btn('<span>♙</span><b>Mitglieder</b>','nav',{page:'roster'},false,'location register')}</div><div class="hall-guidance"><div><span class="eyebrow">DEIN NÄCHSTER SCHRITT</span><p>${!state.recruited?'Drei Gefährten für deine neue Gilde.':!state.parties.length?'Eine Gruppe für das erste Abenteuer.':pending?'Deine Gruppe ist zurückgekehrt.':'Ein Auftrag, eine Geschichte, neue Gefährten.'}</p></div>${btn(!state.recruited?'Gefährten wählen':!state.parties.length?'Gruppe bilden':pending?'Ergebnis ansehen':'Aufträge ansehen','nav',{page:next},false,'primary')}</div><span class="hall-note">Browser-Playtest · Kein Save · Neuladen beginnt eine neue Gilde</span></section>`;}
function memberCard(a,extra=''){return`<article class="card candidate-card class-${a.cls.split('.')[1]} ${selection.has(a.id)?'selected':''}" style="--class:${cls(a).color}"><div class="candidate-art">${portrait(a)}<span class="rank-seal">F${a.level}</span></div><div class="candidate-info"><span class="eyebrow">${cls(a).name}</span><h3>${esc(a.name)}</h3>${badge(cls(a).role)}<p class="candidate-status">Bereit für deine Gilde</p>${extra}</div></article>`;}
function recruit(){const normal=state.recruited,pool=normal?state.normalPool:state.candidates,busy=performance.now()<recruitBusyUntil;return title('Neue Gefährten. Neue Geschichten.',normal?'F1-Gefährten · '+R.recruitmentConfig.candidateCost+' Gold pro Rekrutierung · '+state.members.length+'/'+R.recruitmentConfig.guildCapacity+' Gildenplätze':'Fünf Reisende suchen eine Gilde. Wähle genau drei – kostenlos.')+`<div class="recruit-banner"><span>${normal?'Die Tür deiner Gilde steht neuen Abenteurern offen.':'STARTERREKRUTIERUNG · 3 AUS 5 KOSTENLOS'}</span>${normal?btn('Neue Kandidaten suchen · '+R.recruitmentConfig.refreshCost+' Gold','refreshPool',{pool:state.poolSeq},busy,'quiet'):badge(selection.size+' / 3 gewählt')}</div><div class="grid candidate-grid">${pool.map(a=>memberCard(a,normal?`<div class="candidate-cost"><i class="coin">G</i> ${R.recruitmentConfig.candidateCost} Gold</div>${btn('In die Gilde aufnehmen','hire',{candidate:a.id,pool:state.poolSeq},busy,'primary full')}`:btn(selection.has(a.id)?'✓ Ausgewählt':'Diesen Gefährten wählen','candidate',{id:a.id},!selection.has(a.id)&&selection.size>=3,selection.has(a.id)?'primary full':'full'))).join('')}</div>${!pool.length?empty('Alle Gefährten sind angekommen.','Suche für '+R.recruitmentConfig.refreshCost+' Gold nach fünf neuen Kandidaten.'):''}${!normal?`<div class="selection-bar row spread"><span>${selection.size} / 3 Gefährten ausgewählt</span>${btn('Unsere Geschichte beginnt','recruit',{},selection.size!==3,'primary')}</div>`:''}<p class="footer-note">${normal?'Der erste normale Pool ist kostenlos. Gold und Platz werden vor jeder Aufnahme geprüft.':'Krieger schützen. Priester helfen. Schurken und Magier teilen aus.'}</p>`;}
function gear(a){return`<div class="equipment-slots">${R.slots.map((s,i)=>`<div class="equipment-slot ${a.gear[s]?'filled rarity-common':''}"><span class="slot-icon">${['⚔','♜','⌁'][i]}</span><div><small>${['Waffe','Oberkörper','Beine'][i]}</small><b>${a.gear[s]?esc(R.item(a.gear[s].def).name):'Nicht ausgerüstet'}</b>${a.gear[s]?'<em>Common</em>':''}</div></div>`).join('')}<div class="potion-slot"><span>♧ Heiltrank</span><b>${a.potion} / 1</b></div></div>`;}
function roster(){return title('Deine Gilde. Deine Gefährten.','Jeder Name erzählt eine Geschichte. Fortschritt und Ausrüstung bleiben bei deiner Gilde.')+(state.members.length?`<div class="grid roster-grid">${state.members.map(a=>{const next=R.thresholds[Math.min(a.level,9)],start=R.thresholds[a.level-1],points=(a.level-1)*3,percent=a.level===10?100:(a.xp-start)/(next-start)*100;return`<article class="card roster-card ${a.dead?'is-dead':a.recovery>clock?'is-injured':''}"><div class="roster-top">${portrait(a)}<div><span class="eyebrow">${cls(a).name}</span><h3>${esc(a.name)}</h3><span class="rank-seal">F${a.level}</span><p class="${a.dead?'bad':R.available(a,clock)?'good':''}">${status(a)}</p>${badge(pname(state.parties.find(p=>p.members.includes(a.id))?.id))}</div></div><div class="row spread"><small>${a.xp} / ${next} XP</small><small>${points} Skillpunkte</small></div><div class="progress xp"><i style="width:${percent}%"></i></div>${gear(a)}<details><summary>Talente deiner Klasse</summary>${GuildSkills[a.cls].map((skill,i)=>`<div class="list-row"><span>${skill.name}</span><b>${Math.max(0,Math.floor((points+8-i)/9))}/3</b></div>`).join('')}</details>${a.dead?`<footer>${btn('Aus Gildenregister entfernen …','remove-dead-dialog',{member:a.id},false,'quiet danger full')}</footer>`:''}</article>`;}).join('')}</div>`:empty('Die Halle wartet auf ihre Gefährten.','Rekrutiere deine ersten drei Mitglieder.','recruit'));}
function empty(h,t,dest){return`<section class="empty"><h2>${h}</h2><p>${t}</p>${dest?btn('Weiter','nav',{page:dest},false,'primary'):''}</section>`;}
function parties(){if(!current()&&state.parties.length)party=state.parties[0].id;const p=current(),free=state.members.filter(a=>!a.dead&&!state.parties.some(p=>p.members.includes(a.id)));return title('Gemeinsam aufbrechen.','1–6 Mitglieder. Ein Mitglied gehört höchstens einer Gruppe an.')+picker()+`<div class="two-col"><section class="card"><h2>${p?esc(p.name):'Keine Gruppe ausgewählt'}</h2>${p?`<p class="${R.partyLocked(state,p.id)?'bad':'good'}">${R.partyLocked(state,p.id)?'🔒 Bis zur Quest-Auswertung gesperrt':'Bereit zur Verwaltung'}</p>${p.members.map(id=>{const a=member(id);return`<div class="list-row"><div><b>${esc(a.name)}</b> · ${cls(a).name}<br><small>${status(a)} ${p.leader===id?'· ⚑ Leiter':''}</small></div><div class="row">${btn('Leiter','leader',{member:id},R.partyLocked(state,p.id)||a.dead,'quiet')}${btn('Entfernen','remove',{member:id},R.partyLocked(state,p.id)||p.members.length===1,'quiet')}${state.parties.length>1?btn('Verschieben','transfer-dialog',{member:id},R.partyLocked(state,p.id),'quiet'):''}</div></div>`;}).join('')}<div class="row" style="margin-top:16px">${btn('Leiter leeren','clearLeader',{},R.partyLocked(state,p.id),'quiet')}${btn('Auflösen','dissolve-dialog',{},R.partyLocked(state,p.id),'quiet danger')}${btn('Quest wählen','nav',{page:'quests'},false,'primary')}</div>`:'<p class="muted">Wähle rechts freie Mitglieder und erstelle deine erste Gruppe.</p>'}</section><section class="card"><h2>Freie Mitglieder</h2>${free.length?free.map(a=>`<div class="list-row"><label class="check"><input type="checkbox" data-draft="${a.id}" ${draft.has(a.id)?'checked':''}><span>${esc(a.name)} · ${cls(a).name}<br><small>${status(a)}</small></span></label>${p?btn('+ zur Gruppe','add',{member:a.id},R.partyLocked(state,p.id)||p.members.length>=6,'quiet'):''}</div>`).join(''):'<p class="muted">Alle lebenden Mitglieder sind bereits zugeordnet.</p>'}<footer>${btn(`Neue Gruppe (${draft.size})`,'createParty',{},draft.size<1||draft.size>6,'primary full')}</footer></section></div>`;}
const typeNames=['Sammeln','Lieferung','Monsterjagd','Rettung'],typeIcons=['❧','◇','⚔','✚'];
function quests(){return title('Aufträge am Brett.','F-Rang · normale Gefahr · 60 Sekunden · Empfehlung: 2 Mitglieder')+picker()+`<div class="row spread" style="margin-bottom:15px"><span class="muted">Auswertungsbereite Gruppen belegen weiterhin ihren Questplatz.</span>${btn(showPaid?'Abgeholte ausblenden':'Abgeholte anzeigen','show-paid',{},false,'quiet')}</div><div class="grid">${state.quests.filter(q=>showPaid||!q.paid).map(q=>`<article class="card quest-card ${recentQuest===q.id?'quest-departure':''}"><div class="row spread"><span class="quest-type">${typeIcons[q.type]}</span>${badge(q.status==='Available'?'Verfügbar':q.status==='Active'?'Unterwegs':q.status==='CompletedPendingResolution'?'Rückkehr':'Ausgewertet')}</div><h3 style="margin-top:12px">${q.name}</h3><p class="muted">${typeNames[q.type]} · ${q.distance}</p>${q.status==='Available'?`<small>40 Gold · 60 Gruppen-XP bei Erfolg<br>Beutechance pro Item: 35 %</small><footer>${btn('Mit Gruppe starten','start',{quest:q.id},!current(),'primary full')}</footer>`:q.status==='Active'?`<div class="progress"><i data-progress="${q.id}" style="width:${Math.min(100,(clock-q.start)/q.duration*100)}%"></i></div><p data-countdown="${q.id}">${Math.max(0,Math.ceil((q.end-clock)/1000))}s verbleibend</p><small>${pname(q.party)} · gesperrt</small>`:q.status==='CompletedPendingResolution'?`<p class="good">${pname(q.party)} wartet auf Auswertung.</p>${btn('Ergebnis auswerten','resolve',{quest:q.id},false,'primary full')}`:result(q)}</article>`).join('')}</div><div class="selection-bar row spread"><span>Weitere Instanzen der vier vorhandenen Sample-Aufträge.</span>${btn('Vier Aufträge aushängen','offers',{},state.quests.some(q=>q.status==='Available'))}</div>`;}
function result(q){const r=q.result;return`<div class="quest-result ${r.success?'result-success':'result-failure'}"><h3 class="${r.success?'good':'bad'}">${r.wipe?'Wipe':r.success?'Auftrag erfüllt':r.retreat?'Rechtzeitig zurückgezogen':'Ziel nicht erreicht'}</h3><div class="list-row"><b>+${r.gold} Gold</b><span>${r.members.reduce((n,m)=>n+m.xp,0)} XP gesamt</span></div>${r.members.map(m=>`<div class="list-row"><span>${esc(member(m.id).name)}<br><small class="${m.dead?'bad':''}">${m.dead?'Tot':m.injured?`Verletzt · ${m.seconds}s Erholung`:'Unversehrt'}</small></span><b>+${m.xp} XP</b></div>`).join('')}<p style="margin-top:12px">${r.loot.length?r.loot.map(l=>`<span class="loot-reveal">✦ ${l.qty}× ${R.item(l.def).name}</span>`).join(''):'Keine Beute gefunden.'}</p>${q.paid?badge('Rewards übernommen'):btn('XP, Gold & Beute übernehmen','reward',{quest:q.id},false,'primary full')}${q.paid?btn('Buchung erneut prüfen','reward',{quest:q.id},false,'quiet full'):''}</div>`;}
function storage(){return title('Was der Gilde gehört.','Gemeinsamer Bestand · keine Kapazitätsgrenze · keine Haltbarkeit',btn('Auto-Equip prüfen','equip',{},false,'primary'))+`<div class="notice row spread"><span><b>${state.stock.length}</b> freie Ausrüstungsteile · <b>${state.potions}</b> Heiltränke im Lager</span><small>Tränke werden vor Einsätzen automatisch zugeteilt. Kein Verbrauch im Probekampf.</small></div><div class="two-col"><section class="card"><h2>Gildenlager</h2>${state.stock.length?state.stock.map(e=>`<div class="list-row"><span>${esc(R.item(e.def).name)}<br><small>${e.instance}</small></span>${badge('Common')}</div>`).join(''):'<p class="muted">Keine freie Ausrüstung. Neue Beute wird nach der Reward-Übernahme automatisch bewertet.</p>'}<div class="list-row"><span>Einfacher Heiltrank</span><b>× ${state.potions}</b></div></section><section class="stack">${state.members.map(a=>`<article class="card"><div class="row spread"><h3>${esc(a.name)} · ${cls(a).name}</h3>${badge(status(a))}</div>${gear(a)}<footer>${btn('Ausrüstung & Trank zurückgeben','return',{member:a.id},R.locked(state,a.id),'quiet full')}</footer></article>`).join('')}</section></div>`;}
function combatArena(){if(!combat)return empty('Das Übungsportal ist geöffnet.','Wähle eine freie Gruppe. Hier darfst du kämpfen, ohne deine Gilde zu gefährden.');const s=combat.state;return`<div class="row spread"><h2 id="combat-heading">${s.phase==='TechnicalAbort'?'Technischer Simulationsabbruch':s.result?s.result.wipe?'Gruppe vollständig gefallen':s.result.outcome==='Victory'?'Sieg deiner Gefährten!':'Niederlage':s.phase==='Aftermath'?'Nachsorge':'Die Begegnung beginnt'}</h2><span class="badge" id="combat-clock">${(s.tick/4).toFixed(1)}s</span></div><div class="teams">${['Adventurer','Enemy'].map((side,idx)=>`${idx?'<span class="versus">VS</span>':''}<div class="team">${s.members.filter(a=>a.faction===side).map(a=>`<div data-combatant="${esc(a.id)}" class="fighter ${side==='Enemy'?'enemy':''} life-${a.life}" style="--class:${R.classes[a.def]?.color||'#ba856b'}"><div class="fighter-label"><b>${esc(member(a.id)?.name||a.p.name)}</b><span class="hp-label">${a.hp}/${a.p.hp}</span></div><div class="progress"><i class="hp-value" style="width:${a.hp/a.p.hp*100}%"></i></div>${a.p.mana?`<div class="progress mana"><i class="mana-value" style="width:${a.mana/a.p.mana*100}%"></i></div><small class="mana-label">Mana ${a.mana}/${a.p.mana}</small>`:''}<div class="fighter-stage"><img class="combat-sprite" src="${art(a.def)}" alt="${esc(a.p.name)}"><span class="stun-stars">✦ ✦ ✦</span><div class="combat-fx"></div></div><small class="life-label">${lifeName[a.life]}</small><div class="status-icons">${Object.keys(a.statuses).map(k=>`<span class="status-${k}">${k}</span>`).join('')}</div></div>`).join('')}</div>`).join('')}</div>${s.result?`<p class="footer-note result-banner">${s.result.wipe?'Alle Abenteurer dieser Kampfprobe sind gefallen. ':''}Deine Gilde bleibt unversehrt. ${s.result.participants.filter(x=>x.recovery).length?'Nachsorge: 120s im Folgenvertrag, hier nicht gebucht.':''}</p>`:s.phase==='TechnicalAbort'?'<p class="notice">Die technische Zeitgrenze wurde erreicht. Keine normale Niederlage und keine zusätzlichen Folgen. Starte eine neue Kampfprobe.</p>':''}`;}
const actionLabel=id=>id.split('.').pop().replaceAll('_',' ');
function combatFeedback(events){if(!combat)return;const s=combat.state;const heading=$('#combat-heading');if(heading)heading.textContent=s.phase==='Aftermath'?'Nachsorge':'Die Begegnung läuft';const timer=$('#combat-clock');if(timer)timer.textContent=(s.tick/4).toFixed(1)+'s';
 const cards=[...document.querySelectorAll('[data-combatant]')],card=id=>cards.find(el=>el.dataset.combatant===id);
 for(const a of s.members){const el=card(a.id);if(!el)continue;el.className='fighter '+(a.faction==='Enemy'?'enemy ':'')+'life-'+a.life+(a.statuses.Stun?' stunned':'');el.querySelector('.hp-label').textContent=a.hp+'/'+a.p.hp;el.querySelector('.hp-value').style.width=a.hp/a.p.hp*100+'%';const mana=el.querySelector('.mana-value');if(mana){mana.style.width=a.mana/a.p.mana*100+'%';el.querySelector('.mana-label').textContent='Mana '+a.mana+'/'+a.p.mana;}el.querySelector('.life-label').textContent=lifeName[a.life];el.querySelector('.status-icons').innerHTML=Object.keys(a.statuses).map(k=>`<span class="status-${k}">${k}</span>`).join('');}
 if(reduced())return;
 for(const e of events.slice(-12)){const actor=card(e.actor),target=card(e.target),heal=e.kind.includes('.heal')||e.kind.includes('.stabilize'),death=e.kind.startsWith('death.'),dot=e.kind.startsWith('status.');if(!target||death)continue;
 const sprite=actor?.querySelector('.combat-sprite');if(sprite&&e.actor!==e.target&&!dot&&!heal&&sprite.animate)sprite.animate([{transform:'translateX(0)'},{transform:`translateX(${actor.classList.contains('enemy')?'-':'+'}14px) rotate(-4deg)`},{transform:'translateX(0)'}],{duration:220,easing:'ease-out'});
 const hit=target.querySelector('.combat-sprite');if(hit?.animate)hit.animate(heal?[{filter:'drop-shadow(0 0 0 transparent)'},{filter:'drop-shadow(0 0 14px #a9f18d)'},{filter:'drop-shadow(0 0 0 transparent)'}]:[{transform:'translateX(0)'},{transform:'translateX(-5px)',filter:'brightness(1.7)'},{transform:'translateX(4px)'},{transform:'translateX(0)'}],{duration:e.critical?420:260});
 const fx=target.querySelector('.combat-fx');while(fx.children.length>=3)fx.firstElementChild.remove();const number=document.createElement('span');number.className='combat-number '+(heal?'healing':e.critical?'critical':dot?'dot '+e.kind.split('.')[1]:'damage');number.textContent=(heal?'+':'−')+e.amount+(e.critical?' !':'');fx.appendChild(number);setTimeout(()=>number.remove(),850);}
}
function combatLog(){return combat?combat.log.slice(-12).reverse().map(e=>`<p><span class="muted">${(e.tick/4).toFixed(1)}s</span> ${esc(member(e.actor)?.name||e.actor)} → ${esc(member(e.target)?.name||e.target)}<br><b>${actionLabel(e.kind)} ${e.amount}${e.critical?' · CRIT':''}</b></p>`).join(''):'';}
function combatPage(){return title('Ein Blick in den Kampf.','Isolierter Test: keine Rewards, kein Verbrauch, keine dauerhaften Gildenfolgen.')+picker()+`<div class="row" style="margin-bottom:15px"><select id="enemy" aria-label="Gegnerprofil">${Object.entries(R.profiles).filter(([id])=>id.startsWith('enemy')).map(([id,p])=>`<option value="${id}">${p.name}</option>`).join('')}</select><select id="enemy-count" aria-label="Gegneranzahl">${[1,2,3,4,5,6].map(n=>`<option value="${n}">${n} Gegner</option>`).join('')}</select>${btn('Probekampf starten','combat-start',{},!current(),'primary')}${[0,1,2,4].map(n=>btn(n?n+'×':'Pause','speed',{speed:n},!combat||combat.terminal,'quiet')).join('')}</div><div class="combat-layout"><section class="arena" id="arena">${combatArena()}</section><aside class="card"><h3>Was gerade passiert</h3><div class="battle-log" id="battle-log">${combatLog()}</div><p class="footer-note">Tick: 250ms · Seed 7<br>Equipment, Level und Skills combatneutral.</p></aside></div>`;}
function render(){resources();$('#content').className='screen screen-'+page;$('#nav').innerHTML=pages.map(([id,icon,label])=>`<button data-action="nav" data-page="${id}" class="${id===page?'active':''}" ${id===page?'aria-current="page"':''}><span class="symbol">${icon}</span>${label}</button>`).join('');const old=$('#content').scrollTop;$('#content').innerHTML=({hall,recruit,roster,party:parties,quests,storage,combat:combatPage}[page])();$('#content').scrollTop=old;}
function modal(html){$('#dialog-content').innerHTML=html;if(!$('#dialog').open)$('#dialog').showModal();}
function apply(op,args={}){args.party??=party;const before=state;state=R.change(state,op,args,clock);if(op==='reward'&&state!==before){try{state=R.change(state,'equip',{},clock);}catch(e){toast('Belohnung gebucht. Auto-Equip offen: '+e.message);return;}const raised=state.members.filter(a=>a.level>(before.members.find(b=>b.id===a.id)?.level||a.level));moment(raised.length?'level-up':'reward',raised.length?raised.map(a=>a.name+' erreicht F'+a.level+' · +'+((a.level-before.members.find(b=>b.id===a.id).level)*3)+' Skillpunkte').join(' · '):(()=>{const r=state.quests.find(q=>q.id===args.quest).result;return '+'+r.gold+' Gold · +'+r.members.reduce((n,m)=>n+m.xp,0)+' XP · '+r.loot.length+' Beutefunde';})());}
 if(op==='start'){recentQuest=args.quest;moment('departure','Deine Gefährten brechen auf!');setTimeout(()=>recentQuest='',650);}
 if(op==='hire'){lockRecruit();moment('arrival',state.members.at(-1).name+' tritt deiner Gilde bei · −'+R.recruitmentConfig.candidateCost+' Gold');}
 if(op==='refreshPool'){lockRecruit();moment('arrival','Neue Gefährten sind angekommen · −'+R.recruitmentConfig.refreshCost+' Gold');}
 toast(op==='reward'&&state===before?'Bereits gebucht – keine doppelte Belohnung.':({recruit:'Drei Gefährten sind angekommen. Der erste normale Pool ist kostenlos bereit.',createParty:'Eine neue Gruppe ist bereit.',start:'Gruppe aufgebrochen.',resolve:'Die Gruppe ist zurück. Belohnung jetzt übernehmen.',reward:'XP, Gold und Beute übernommen.',equip:'Ausrüstung neu bewertet.',hire:'Neues Mitglied aufgenommen.',refreshPool:'Fünf neue Kandidaten warten.',removeDead:'Ein Platz im Gildenregister ist frei.'}[op]||'Erledigt.'));}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const d=el.dataset;try{switch(d.action){case'nav':go(d.page);return;case'pick':party=d.id;break;case'candidate':selection.has(d.id)?selection.delete(d.id):selection.add(d.id);break;case'recruit':apply('recruit',{ids:[...selection]});go('party');return;case'hire':if(performance.now()<recruitBusyUntil)return;apply('hire',{candidate:d.candidate,pool:Number(d.pool)});break;case'refreshPool':if(performance.now()<recruitBusyUntil)return;apply('refreshPool',{pool:Number(d.pool)});break;case'remove-dead-dialog':modal(`<h2>${esc(member(d.member).name)} endgültig aus dem Gildenregister entfernen?</h2><p>Nur dieser verstorbene Gefährte wird dauerhaft aus der aktuellen Gilde entfernt. Der Platz wird frei. Diese Aktion kann nicht rückgängig gemacht werden.</p>${btn('Endgültig entfernen','removeDead',{member:d.member},false,'danger')}`);return;case'removeDead':apply('removeDead',{member:d.member,confirmed:true});$('#dialog').close();break;case'createParty':apply('createParty',{ids:[...draft]});draft.clear();party=state.parties.at(-1).id;break;case'show-paid':showPaid=!showPaid;break;
 case'transfer-dialog':modal(`<h2>Mitglied verschieben</h2><p>${esc(member(d.member).name)} aus ${esc(pname(party))}</p><div class="stack">${state.parties.filter(p=>p.id!==party).map(p=>btn(p.name,'transfer',{member:d.member,to:p.id},R.partyLocked(state,p.id)||p.members.length>=6)).join('')}</div>`);return;
 case'dissolve-dialog':modal(`<h2>Gruppe auflösen?</h2><p>Alle Mitglieder werden frei. Es gehen keine Mitglieder oder Items verloren.</p>${btn('Gruppe auflösen','dissolve',{},false,'danger')}`);return;
 case'transfer':apply('transfer',{member:d.member,to:d.to});$('#dialog').close();break;case'dissolve':apply('dissolve');party='';$('#dialog').close();break;
 case'leader':case'remove':case'add':case'return':apply(d.action,{member:d.member});draft.delete(d.member);break;
 case'clearLeader':case'offers':case'equip':apply(d.action);break;
 case'start':case'resolve':case'reward':apply(d.action,{quest:d.quest});break;
 case'combat-start':{const p=current();if(!p||R.partyLocked(state,p.id)||p.members.some(id=>!R.available(member(id),clock)||R.locked(state,id)))throw Error('Die gesamte Gruppe muss frei und einsatzfähig sein.');const inputs=p.members.map(id=>{const a=member(id);return C.input(a.id,a.cls,a.id,R.slots.map(s=>a.gear[s]));});for(let i=0;i<Number($('#enemy-count').value);i++)inputs.push(C.input('enemy.'+i,$('#enemy').value));combat=new C.Combat(inputs,7);toast('Probekampf gestartet – Gildenbestand bleibt unverändert.');break;}
 case'speed':if(combat&&!combat.terminal){combat.speed=Number(d.speed);toast(combat.speed?combat.speed+'×':'Kampf pausiert');}return;
 case'advance':clock+=60000;R.refresh(state,clock);toast('Entwicklungsuhr +60s.');break;
 case'reset-confirm':modal(`<h2>Neue Gilde beginnen?</h2><p>Der aktuelle Prototyp-Spielstand geht verloren.</p>${btn('Zurücksetzen','reset',{},false,'danger')}`);return;
 case'reset':state=R.initial();shownGold=null;recruitBusyUntil=0;combat=null;party='';selection.clear();draft.clear();clock=1000;showPaid=false;$('#dialog').close();go('hall');toast('Neue Gilde gestartet.');return;
 case'about':modal('<h2>Browser-Playtest</h2><p>Eigenständige JavaScript-Umsetzung. Kein Unity-Build und kein Save.</p><p>Bestehende Questformeln, F1–F10-XP, 3 Skillpunkte/Level, Itemkatalog, Sperren und Combatregeln sind übernommen.</p><p>JavaScript-Zahlen statt C# decimal; Item-/Result-IDs sind browserlokal. Grafik ist eine 2D-Präsentation. Kampfresultate werden nicht in die Gilde gebucht.</p><p>Nach der Starterrunde: F1-Rekrutierung für 50 Gold, neue Kandidaten für 25 Gold. Verstorbene können nach Abholung offener Belohnungen bestätigt entfernt werden. Kein Save und keine Wiederbelebung.</p>');return;
 }render();}catch(err){toast(err.message);}});
document.addEventListener('change',e=>{if(e.target.dataset.draft){const id=e.target.dataset.draft;e.target.checked?draft.add(id):draft.delete(id);render();}});
$('#tools').onclick=()=>modal(`<h2>Playtest-Werkzeuge</h2><p>Kein Save. Die Uhr läuft während der Sitzung. Entwicklungsaktionen ändern keine Spielregel.</p><div class="stack">${btn('+60s Quest / Erholung','advance')}${btn('Neue Gilde …','reset-confirm',{},false,'danger')}${btn('Regeln & Unterschiede','about')}</div>`);
document.addEventListener('visibilitychange',()=>{if(document.hidden&&combat)combat.speed=0;});
setInterval(()=>{const n=performance.now(),dt=n-previous;previous=n;clock+=dt;let changed=state.quests.filter(q=>q.status==='Active'&&clock>=q.end).length;R.refresh(state,clock);resources();if(changed){render();moment('returning','Deine Gefährten sind zurück!');toast('Eine Gruppe wartet auf Auswertung.');}
 for(const el of document.querySelectorAll('[data-countdown]')){const q=state.quests.find(q=>q.id===el.dataset.countdown);el.textContent=Math.max(0,Math.ceil((q.end-clock)/1000))+'s verbleibend';}
 for(const el of document.querySelectorAll('[data-progress]')){const q=state.quests.find(q=>q.id===el.dataset.progress);el.style.width=Math.min(100,(clock-q.start)/q.duration*100)+'%';}
 if(page==='combat'&&combat&&!combat.terminal&&combat.speed){const tick=combat.state.tick;combat.advance(Math.min(dt,2000));combatFeedback(combat.log.filter(e=>e.tick>tick));$('#battle-log').innerHTML=combatLog();if(combat.terminal){render();moment(combat.state.phase==='TechnicalAbort'?'technical':combat.state.result?.outcome==='Victory'?'victory':'defeat',combat.state.phase==='TechnicalAbort'?'Technische Zeitgrenze · keine Niederlage':combat.state.result?.wipe?'Die Gruppe ist gefallen':combat.state.result?.outcome==='Victory'?'Sieg deiner Gefährten!':'Deine Gruppe wurde besiegt');}}
},250);
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 const tools=[{name:'read_guild_playtest',description:'Read the current in-memory guild playtest snapshot. No mutation.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>R.clone({page,clock,state,combat:combat?.state||null})},
 {name:'navigate_guild_playtest',description:'Navigate to a guild screen. Leaving combat pauses the practice fight.',inputSchema:{type:'object',properties:{page:{type:'string',enum:pages.map(p=>p[0])}},required:['page'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!pages.some(p=>p[0]===input.page))throw Error('Unknown page');go(input.page);return{page};}}];
 for(const tool of tools)try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch(_){}
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
render();
})();
