/* Explicit local save contract. No Combat sessions or presentation state are persisted. */
(function(g){'use strict';const R=g.GuildRules,P=g.GuildProgression,N=g.GuildRecruitment,D=g.GuildDungeon;
const LEGACY_VERSION='guildgame.browser.save.v1',VERSION='guildgame.browser.save.v2',DUNGEON_VERSION='guildgame.browser.save.v3',KEYS=Object.freeze({primary:'guildgame.browser.save.primary',backup:'guildgame.browser.save.backup'}),MAX_BYTES=2*1024*1024;
const fail=m=>{throw Error('Spielstand: '+m);},copy=R.clone;
function obj(x,keys){if(!x||typeof x!=='object'||Array.isArray(x)||Object.keys(x).sort().join('|')!==keys.slice().sort().join('|'))fail('Ungültige Struktur ('+keys[0]+')');}
const num=(n,min=0,max=Number.MAX_SAFE_INTEGER)=>{if(!Number.isSafeInteger(n)||n<min||n>max)fail('Ungültige Ganzzahl');};
const real=(n,min=0,max=Number.MAX_SAFE_INTEGER)=>{if(!Number.isFinite(n)||n<min||n>max)fail('Ungültiger Zahlenwert');};
const bool=x=>{if(typeof x!=='boolean')fail('Ungültiger Wahrheitswert');};
const str=(x,max=160)=>{if(typeof x!=='string'||!x.length||x.length>max||/[\u0000-\u001f]/.test(x))fail('Ungültiger Text/ID');};
const list=(a,max=10000)=>{if(!Array.isArray(a)||a.length>max)fail('Ungültige Liste');};
const unique=a=>{if(new Set(a).size!==a.length)fail('Doppelte ID');};
function gearOut(e){return e?{def:e.def,instance:e.instance,rarity:R.item(e.def)?.rarity}:null;}
function memberOut(a){return{id:a.id,name:a.name,cls:a.cls,rank:a.rank||'F',level:a.level,xp:a.xp,dead:a.dead,recovery:a.recovery,leadership:a.leadership,boldness:a.boldness,gear:Object.fromEntries(R.slots.map(k=>[k,gearOut(a.gear[k])])),potion:a.potion};}
function resultOut(r){return r?{guildXP:r.guildXP,success:r.success,retreat:r.retreat,wipe:r.wipe,power:r.power,difficulty:r.difficulty,ratio:r.ratio,overload:r.overload,members:r.members.map(m=>({id:m.id,incap:m.incap,stabilized:m.stabilized,dead:m.dead,injured:m.injured,seconds:m.seconds,xp:m.xp})),gold:r.gold,loot:r.loot.map(l=>({def:l.def,qty:l.qty}))}:null;}
function createSaveData(s,clock,now=Date.now()){const d={saveVersion:D?DUNGEON_VERSION:VERSION,...(D?{expeditions:copy(s.expeditions||{...D.empty(),portalAnnounced:P.guildLevel(s)>=2})}:{}),rulesVersion:P.config.version,savedAt:now,clock,questBoard:s.questBoard?copy(s.questBoard):null,guild:{xp:s.guild.xp,level:P.guildLevel(s)},recruitment:{recruited:s.recruited,poolSeq:s.poolSeq,poolGuildLevel:s.poolGuildLevel??1,candidates:s.candidates.map(memberOut),normalPool:s.normalPool.map(memberOut)},members:s.members.map(memberOut),retiredMembers:s.retiredMembers.map(a=>({id:a.id,name:a.name,cls:a.cls,level:a.level})),parties:s.parties.map(p=>({id:p.id,name:p.name,members:p.members.slice(),leader:p.leader})),quests:s.quests.map(q=>({id:q.id,name:q.name,type:q.type,distance:q.distance,status:q.status,duration:q.duration,size:q.size,gold:q.gold,xp:q.xp,party:q.party,participants:q.participants.slice(),result:resultOut(q.result),paid:q.paid,tier:q.tier,recommended:q.recommended,start:q.start??null,end:q.end??null,dynamic:q.dynamic?copy(q.dynamic):null})),inventory:{gold:s.gold,stock:s.stock.map(gearOut),potions:s.potions,itemSeq:s.itemSeq},counters:{partySeq:s.partySeq,offerSeq:s.offerSeq}};validateSaveData(d);return d;}
function validateSaveData(d){
 const legacy=d?.saveVersion===LEGACY_VERSION,dungeon=d?.saveVersion===DUNGEON_VERSION;obj(d,[...(dungeon?['expeditions']:[]),...(legacy?[]:['questBoard']),'saveVersion','rulesVersion','savedAt','clock','guild','recruitment','members','retiredMembers','parties','quests','inventory','counters']);if(d.saveVersion!==VERSION&&!legacy&&!(dungeon&&D))fail('Unbekannte SaveVersion – Datei unverändert behalten.');if(d.rulesVersion!==P.config.version)fail('Nicht unterstützte Spielregelversion');num(d.savedAt,0,8640000000000000);real(d.clock,0,1e15);
 obj(d.guild,['xp','level']);num(d.guild.xp,0,1000);num(d.guild.level,1,5);if(P.guildLevel({guild:d.guild})!==d.guild.level)fail('Gilden-Level passt nicht zu XP');
 obj(d.inventory,['gold','stock','potions','itemSeq']);num(d.inventory.gold);num(d.inventory.potions,0,1000000);num(d.inventory.itemSeq,0,1000000000);list(d.inventory.stock);obj(d.counters,['partySeq','offerSeq']);num(d.counters.partySeq,0,1000000000);num(d.counters.offerSeq,0,1000000000);
 obj(d.recruitment,['recruited','poolSeq','poolGuildLevel','candidates','normalPool']);const rec=d.recruitment;bool(rec.recruited);num(rec.poolSeq,0,1000000000);num(rec.poolGuildLevel,1,d.guild.level);list(rec.candidates,5);list(rec.normalPool,5);if(rec.candidates.length!==5||(!rec.recruited&&(rec.poolSeq!==0||rec.normalPool.length||d.members.length))||(rec.recruited&&rec.poolSeq<1))fail('Rekrutierungszustand ungültig');
 list(d.members,20);list(d.retiredMembers);list(d.parties,5);list(d.quests);const instances=[];
 function checkItem(e,collect=true){obj(e,['def','instance','rarity']);const it=R.item(e.def);if(!it?.slot||e.rarity!==it.rarity)fail('Unbekannte Itemdefinition/Rarity');str(e.instance);const match=/^browser\.item\.(\d{8,})$/.exec(e.instance);if(!match||Number(match[1])<1||Number(match[1])>d.inventory.itemSeq)fail('Item-ID/Counter ungültig');if(collect)instances.push(e.instance);}
 function checkMember(a,candidate=false){obj(a,['id','name','cls','rank','level','xp','dead','recovery','leadership','boldness','gear','potion']);str(a.id);str(a.name,80);if(!R.classes[a.cls]||a.rank!=='F')fail('Unbekannte Klasse/Rang');num(a.level,1,10);num(a.xp,0,630);if(R.level(a.xp)!==a.level)fail('Level/XP widersprüchlich');bool(a.dead);real(a.recovery,0,1e15);real(a.leadership,0,1);real(a.boldness,-1,1);num(a.potion,0,1);obj(a.gear,R.slots);for(const slot of R.slots)if(a.gear[slot]){checkItem(a.gear[slot],!candidate);const it=R.item(a.gear[slot].def);if(it.slot!==slot||!it.allowed.includes(a.cls))fail('Inkompatibles Equipment');}if(a.dead&&(a.recovery||a.potion||Object.values(a.gear).some(Boolean)))fail('Toter mit aktivem Besitz/Erholung');if(candidate&&(a.dead||a.recovery||a.potion||Object.values(a.gear).some(Boolean)||a.level>8||a.xp!==R.thresholds[a.level-1]))fail('Kandidat ungültig');}
 rec.candidates.forEach(a=>checkMember(a,true));rec.normalPool.forEach(a=>checkMember(a,true));d.members.forEach(a=>checkMember(a));d.inventory.stock.forEach(e=>checkItem(e));unique(instances);
 const starter=R.candidates();rec.candidates.forEach((a,i)=>{if(a.id!==starter[i].id||a.cls!==starter[i].cls||a.name!==starter[i].name||a.level!==1||a.xp!==0)fail('Starterpool geändert');});unique(rec.candidates.map(a=>a.id));unique(rec.normalPool.map(a=>a.id));
 const starterIds=new Set(starter.map(a=>a.id));function knownMemberId(id){if(starterIds.has(id))return;const m=/^browser\.candidate\.(\d+)\.([0-4])$/.exec(id);if(!m||Number(m[1])<1||Number(m[1])>rec.poolSeq)fail('Mitglieds-ID/Counter ungültig');}
 const [min,max]=N.config.ranges[rec.poolGuildLevel-1];rec.normalPool.forEach(a=>{if(!a.id.startsWith('browser.candidate.'+rec.poolSeq+'.')||!/^browser\.candidate\.\d+\.[0-4]$/.test(a.id)||a.level<min||a.level>max)fail('Pool-ID oder Levelgrenze ungültig');});
 d.retiredMembers.forEach(a=>{obj(a,['id','name','cls','level']);str(a.id);str(a.name,80);if(!R.classes[a.cls])fail('Archivklasse');num(a.level,1,10);});const all=[...d.members,...d.retiredMembers];all.forEach(a=>knownMemberId(a.id));unique(all.map(a=>a.id));if(rec.normalPool.some(a=>all.some(m=>m.id===a.id)))fail('Kandidat schon rekrutiert');
 const allIds=new Set(all.map(a=>a.id)),liveIds=new Set(d.members.map(a=>a.id));unique(d.parties.map(p=>p.id));unique(d.quests.map(q=>q.id));
 function generated(id,cat,max){str(id);const n=Number(id.slice(-12));if(n<1||n>max||R.guid(cat,n)!==id)fail('Generierte ID/Counter ungültig');}
 for(const p of d.parties){obj(p,['id','name','members','leader']);generated(p.id,1,d.counters.partySeq);str(p.name,80);list(p.members,6);unique(p.members);if(!p.members.length||p.members.some(id=>!liveIds.has(id))||(p.leader!==null&&!p.members.includes(p.leader)))fail('Gruppe/Leiter ungültig');}
 const bound=new Set(),boundParties=new Set();
 for(const q of d.quests){obj(q,[...(legacy?[]:['dynamic']),'id','name','type','distance','status','duration','size','gold','xp','party','participants','result','paid','tier','recommended','start','end']);generated(q.id,2,d.counters.offerSeq);str(q.name);num(q.type,0,3);if(!['Nah','Mittel','Weit'].includes(q.distance)||!['Available','Active','CompletedPendingResolution','Resolved'].includes(q.status))fail('Questtyp/Status');const base=P.config.tiers.find(t=>t.id===q.tier);if(!base||q.size!==2)fail('Questbalance geändert');let t=base;if(!legacy&&q.dynamic!==null){validateDynamic(q,d);t=P.tier(q);}else if(q.duration!==base.duration||q.gold!==base.gold||q.xp!==base.xp||q.recommended!==base.recommended)fail('Questbalance geändert');bool(q.paid);list(q.participants,6);unique(q.participants);
 if(q.status==='Available'){if(q.party!==null||q.start!==null||q.end!==null||q.participants.length||q.result!==null||q.paid)fail('Angebot hat Laufzeitdaten');continue;}
 generated(q.party,1,d.counters.partySeq);real(q.start,0,d.clock);real(q.end,q.start,1e15);if(q.end!==q.start+q.duration||!q.participants.length||q.participants.some(id=>!allIds.has(id)))fail('Questzeit/Teilnehmer');
 if(q.status==='Active'||q.status==='CompletedPendingResolution'){if(q.result!==null||q.paid)fail('Gebundene Quest bereits bezahlt');const p=d.parties.find(p=>p.id===q.party);if(!p||p.members.slice().sort().join('|')!==q.participants.slice().sort().join('|'))fail('Questbindung verloren');if(boundParties.has(p.id))fail('Gruppe doppelt gebunden');boundParties.add(p.id);for(const id of q.participants){if(bound.has(id)||!liveIds.has(id)||d.members.find(a=>a.id===id).dead)fail('Teilnehmerbindung ungültig');bound.add(id);}if(q.status==='CompletedPendingResolution'&&q.end>d.clock)fail('Quest noch nicht fällig');continue;}
 if(q.end>d.clock)fail('Zu früh ausgewertet');const r=q.result;obj(r,['guildXP','success','retreat','wipe','power','difficulty','ratio','overload','members','gold','loot']);for(const k of ['success','retreat','wipe'])bool(r[k]);if(r.success&&r.retreat)fail('Erfolg und Rückzug widersprüchlich');for(const k of ['power','difficulty','ratio','overload'])real(r[k]);if(r.difficulty!==q.recommended||r.overload>1)fail('Resultwerte ungültig');list(r.members,6);unique(r.members.map(m=>m.id));if(r.members.map(m=>m.id).sort().join('|')!==q.participants.slice().sort().join('|'))fail('Resultteilnehmer');const factor=r.wipe?0:r.success?1:r.retreat?.35:.2;
 for(const m of r.members){obj(m,['id','incap','stabilized','dead','injured','seconds','xp']);for(const k of ['incap','stabilized','dead','injured'])bool(m[k]);num(m.seconds,0,300);num(m.xp,0,q.xp);if(m.xp!==(m.dead?0:Math.floor(q.xp*factor/q.participants.length))||(m.dead&&m.injured)||(m.stabilized&&(!m.incap||m.dead))||(m.dead&&!m.incap)||(m.injured?m.seconds<60:m.seconds!==0))fail('Lebens-/XP-Folge ungültig');}
 if(r.wipe!==r.members.every(m=>m.dead))fail('Wipe widersprüchlich');if(r.gold!==(r.success&&!r.wipe?q.gold:0)||r.guildXP!==(r.success&&!r.wipe?t.guildXP:0))fail('Belohnungswerte ungültig');list(r.loot,7);unique(r.loot.map(l=>l.def.replace(/\.(common|uncommon|rare)$/,'')));for(const l of r.loot){obj(l,['def','qty']);const it=R.item(l.def);if(!it||l.qty!==(it.slot?1:2)||(it.slot&&t.rarities[it.rarity]===0)||!r.success||r.wipe)fail('Loot ungültig');}if(!q.paid&&q.participants.some(id=>!liveIds.has(id)))fail('Offene Rewards ohne Empfänger');
 }
 if(!legacy&&d.questBoard===null&&d.quests.some(q=>q.dynamic!==null))fail('Questboard fehlt');
 if(!legacy&&d.questBoard!==null){validateBoard(d.questBoard,d);const newest=d.quests.filter(q=>q.dynamic?.generationSequence===d.questBoard.generationSequence);if(!newest.length||newest.some(q=>['benchmarkPower','guildLevelAtGeneration','generationSequence','rulesVersion'].some(k=>q.dynamic[k]!==d.questBoard[k])))fail('Boardvertrag widersprüchlich');if(d.questBoard.generationSequence!==Math.ceil(d.counters.offerSeq/4))fail('Boardzähler widersprüchlich');}
 const s=restore(d);R.validate(s);P.validate(s);if(dungeon){D.validate(s,true);for(const run of s.expeditions.runs)if(run.start>d.clock||run.lastTime>d.clock||run.encounters.some(e=>e.endedAt>d.clock)||(run.finishedAt!==null&&run.finishedAt>d.clock))fail('Dungeonzeit liegt in der Zukunft');}return true;
}
function restore(d){const gear=e=>e?{def:e.def,instance:e.instance}:null,member=a=>({...copy(a),gear:Object.fromEntries(R.slots.map(k=>[k,gear(a.gear[k])]))});return{...(d.expeditions?{expeditions:copy(d.expeditions)}:D?{expeditions:{...D.empty(),portalAnnounced:d.guild.level>=2}}:{}),...(d.questBoard?{questBoard:copy(d.questBoard)}:{}),guild:{xp:d.guild.xp},recruited:d.recruitment.recruited,poolSeq:d.recruitment.poolSeq,poolGuildLevel:d.recruitment.poolGuildLevel,candidates:d.recruitment.candidates.map(member),normalPool:d.recruitment.normalPool.map(member),members:d.members.map(member),retiredMembers:copy(d.retiredMembers),parties:copy(d.parties),quests:d.quests.map(q=>{const out=copy(q);if(out.dynamic===null)delete out.dynamic;if(out.start===null){delete out.start;delete out.end;}return out;}),gold:d.inventory.gold,stock:d.inventory.stock.map(gear),potions:d.inventory.potions,itemSeq:d.inventory.itemSeq,partySeq:d.counters.partySeq,offerSeq:d.counters.offerSeq};}
function validateBoard(b,d){obj(b,['benchmarkPower','guildLevelAtGeneration','generationSequence','rulesVersion']);const D=g.GuildDynamicQuests;if(!D||b.rulesVersion!==D.config.version)fail('Unbekannter Questregelvertrag');num(b.guildLevelAtGeneration,1,d.guild.level);num(b.benchmarkPower,D.config.benchmarkFloors[b.guildLevelAtGeneration-1],D.config.maxBenchmark);num(b.generationSequence,1,Math.ceil(d.counters.offerSeq/4));}
function validateDynamic(q,d){const b=q.dynamic;obj(b,['benchmarkPower','guildLevelAtGeneration','generationSequence','rulesVersion','guildXP','drop','rarities','variation']);const board=Object.fromEntries(['benchmarkPower','guildLevelAtGeneration','generationSequence','rulesVersion'].map(k=>[k,b[k]]));validateBoard(board,d);const n=Number(q.id.slice(-12)),index=(n-1)%4;if(Math.ceil(n/4)!==b.generationSequence)fail('Questgeneration/ID widersprüchlich');const expected=g.GuildDynamicQuests.values(board,index);for(const k of ['type','distance','tier','recommended','gold','xp','duration'])if(q[k]!==expected[k])fail('Dynamischer Questwert verändert');for(const k of ['guildXP','drop','variation'])if(b[k]!==expected.dynamic[k])fail('Dynamischer Rewardvertrag verändert');if(!Array.isArray(b.rarities)||b.rarities.length!==3||b.rarities.some((v,i)=>v!==expected.dynamic.rarities[i]))fail('Rarityvertrag verändert');}
function migrateSave(data){if(data?.saveVersion===LEGACY_VERSION){validateSaveData(data);const d=copy(data);d.saveVersion=VERSION;d.questBoard=null;d.quests.forEach(q=>q.dynamic=null);validateSaveData(d);return D?migrateSave(d):d;}if(data?.saveVersion===VERSION){validateSaveData(data);const d=copy(data);if(D){d.saveVersion=DUNGEON_VERSION;d.expeditions={...D.empty(),portalAnnounced:d.guild.level>=2};validateSaveData(d);}return d;}if(data?.saveVersion===DUNGEON_VERSION&&D){validateSaveData(data);return copy(data);}fail('Nicht unterstützte SaveVersion; keine automatische Migration verfügbar.');}
function parse(text){if(typeof text!=='string'||new TextEncoder().encode(text).length>MAX_BYTES)fail('Datei größer als 2 MiB oder kein Text');let d;try{d=JSON.parse(text);}catch(_){fail('JSON beschädigt');}d=migrateSave(d);validateSaveData(d);return d;}
function loaded(d,now){real(now,0,8640000000000000);const clock=d.clock+Math.max(0,now-d.savedAt);real(clock,0,1e15);let state=restore(d);R.refresh(state,clock);if(D)state=D.advance(state,clock);return{state,clock};}
function createStore(storage){let expected,ready=false,blocked=false;
 function read(){try{return storage.getItem(KEYS.primary);}catch(_){fail('Lokaler Speicher nicht verfügbar. Export sichern.');}}
 function loadGame(now=Date.now()){const primary=read();expected=primary;ready=true;let backup;try{backup=storage.getItem(KEYS.backup);}catch(_){blocked=true;fail('Backup-Speicher nicht lesbar');}if(primary===null&&backup===null){blocked=false;return{kind:'empty'};}try{if(primary!==null){const d=parse(primary);blocked=false;return{kind:'primary',...loaded(d,now)};}}catch(_){}try{if(backup!==null){const d=parse(backup);blocked=false;return{kind:'backup',message:'Primary beschädigt oder fehlt. Gültiges Backup geladen.',...loaded(d,now)};}}catch(_){}blocked=true;return{kind:'corrupt',message:'Primary und Backup nicht verwendbar. Nichts wurde überschrieben. Importieren oder Neue Gilde ausdrücklich bestätigen.'};}
 function write(text,replace=false){if(!ready)loadGame();if(blocked&&!replace)fail('Beschädigte Saves geschützt. Erst gültig importieren oder Neue Gilde bestätigen.');if(read()!==expected)fail('Spielstand in einem anderen Tab geändert. Hier nicht überschreiben; Seite neu laden oder exportieren.');let oldValid=false;try{if(expected!==null){parse(expected);oldValid=true;}}catch(_){}try{if(oldValid)storage.setItem(KEYS.backup,expected);storage.setItem(KEYS.primary,text);}catch(_){fail('Speichern fehlgeschlagen (Speicher gesperrt/voll). Aktuellen Stand exportieren.');}expected=text;blocked=false;return true;}
 function saveGame(state,clock,now=Date.now()){const d=createSaveData(state,clock,now),text=JSON.stringify(d);if(new TextEncoder().encode(text).length>MAX_BYTES)fail('Spielstand überschreitet 2 MiB.');write(text);return d;}
 function exportSave(state,clock,now=Date.now()){return JSON.stringify(createSaveData(state,clock,now),null,2);}
 function importSave(text,now=Date.now()){const d=parse(text),result=loaded(d,now),canonical=createSaveData(result.state,result.clock,now);write(JSON.stringify(canonical),true);return result;}
 function deleteSave(confirmed=false){if(confirmed!==true)fail('Löschen muss bestätigt werden');if(!ready)loadGame();if(read()!==expected)fail('Anderer Tab hat den Save geändert; vor Löschen neu laden.');try{storage.removeItem(KEYS.backup);storage.removeItem(KEYS.primary);}catch(_){fail('Spielstand konnte nicht vollständig gelöscht werden. Kein neuer Stand geschrieben.');}expected=null;blocked=false;return true;}
 return{loadGame,saveGame,exportSave,importSave,deleteSave};
}
g.GuildSave={VERSION:D?DUNGEON_VERSION:VERSION,LEGACY_VERSION,KEYS,MAX_BYTES,createSaveData,validateSaveData,migrateSave,parse,restore,loaded,createStore};if(typeof module!=='undefined')module.exports=g.GuildSave;
})(typeof globalThis!=='undefined'?globalThis:window);
